"""Parallel copy/type/shot/motion composition for Maylynn Round 2C."""
from __future__ import annotations

from typing import Any


def build_creative_composition(snapshot: dict[str, Any], experience: dict[str, Any]) -> dict[str, Any]:
    copy = {
        "V01": {"kicker": "OYAMA / EXTERIOR & ROOF", "headline": ["塗る前に、", "まず状態を見る。"], "lead": "外壁のひび、剥がれ、屋根の傷み。\n小山市で、外壁・屋根を修繕・塗装します。\n屋根や高所は、ドローンを使った現地調査に対応しています。気になる点は相談時に確認できます。", "facts": ["小山市中心", "DRONE SURVEY", "最長15年保証"]},
        "V02": {"kicker": "01 / SIGNS", "headline": ["住まいは、", "先にサインを出す。"], "lead": "色あせ、ひび割れ、剥がれ、コケやカビ。\n屋根の破損が気になるときも、雨漏りにつながる前にご相談ください。", "labels": ["ひび割れ", "剥がれ", "色あせ", "コケ・カビ", "屋根の傷み"]},
        "V03": {"kicker": "02 / SCOPE", "headline": ["外壁だけで、", "終わらない。"], "lead": "外壁・屋根の修繕と外装の改装まで。\n状態と希望から、内容を考えます。", "scope": ["外壁", "屋根", "高所調査", "修繕・改装"]},
        "V04": {"kicker": "03 / INSPECTION", "headline": ["見えない屋根は、", "ドローンで見る。"], "lead": "高所を確認し、対応を整理します。", "metrics": [{"label": "DRONE", "value": "高所現地調査"}, {"label": "MAX", "value": "15年", "note": "保証"}, {"label": "DAYS", "value": "7–9", "note": "一軒家の目安"}, {"label": "COLORS", "value": "654", "note": "選べる色数"}]},
        "V05": {"kicker": "04 / PROCESS", "headline": ["見て、決めて、塗る。"], "lead": "状態を確かめ、次を整理します。", "steps": ["見て｜現地の状態を確認する", "決めて｜内容と見積を確認する", "塗る｜段取りをして施工する"], "proof": "20年以上の経験を持つ職人"},
        "V06": {"kicker": "05 / PUBLIC EVIDENCE", "headline": ["公開情報から、", "工事の内容を確かめる。"], "lead": "公開案件とレビューから、工事の範囲や条件を確認できます。見えない点は相談時に確認します。", "cards": [{"label": "OFFICIAL PROJECT", "title": "築40年住宅の塗装工事", "body": "料金5万円〜程度 / 工期1〜2日程度", "source": "公式施工実績"}, {"label": "PUBLIC REVIEW · 1", "title": "築45年戸建 / 外壁塗装", "body": "2025年施工完了 / 68万円 / 15日", "source": "リショップナビ公開レビュー"}]},
        "V07": {"kicker": "06 / MATERIAL", "headline": ["色は654通り。", "塗料は、住まいに合わせて。"], "lead": "公式FAQで日塗工654色を案内しています。塗料の性能も確認できます。", "footnote": "画面上の色は実色再現ではありません。"},
        "V08": {"kicker": "07 / FAQ", "headline": ["相談する前に、", "ここまで分かる。"], "items": [["保証は？", "最長15年。"], ["工期目安は？", "一軒家7〜9日。"], ["色は？", "654色。"], ["どの地域？", "小山市を中心に周辺エリア。"], ["連絡可能時間？", "公式掲載10:00〜19:00。"]]},
        "V09": {"kicker": "08 / ACTION", "headline": ["気になるところを、", "まず見せてください。"], "lead": "外壁のひび、屋根の色あせ、剥がれ。\n相談内容を工事名に整理する前に、今見えている状態を伝えるところから。", "primary_action": "電話で相談する", "secondary_action": "フォームで問い合わせる", "phone": "0800-8080-886", "support": ["受付 10:00〜19:00", "栃木県小山市を中心に周辺エリア"]},
    }
    typography = {"display": "Zen Kaku Gothic New", "body": "Noto Sans JP", "data": "IBM Plex Mono", "display_weight": 600, "hero_desktop": "clamp(4.5rem, 7vw, 7rem)", "hero_mobile": "clamp(2.5rem, 11vw, 3.15rem)", "section_heading": "clamp(2.5rem, 4.4vw, 4.6rem)", "body_size": "1rem", "lead_size": "clamp(1.1rem, 1.7vw, 1.35rem)", "line_break_policy": "meaning_chunk_only"}
    shots = [
        {"shot_id": "S01", "viewport_id": "V01", "shot_type": "EXPLANATION / CONTEXT", "asset_role": "hero_home_finish", "subject": "日本の戸建外観と状態を確認する入口", "moment": "inspection前の観察", "distance": "medium-wide", "camera_angle": "eye-level", "crop": "desktop split / mobile 4:3", "information_purpose": "condition_first_entry", "emotion": "quiet confidence", "evidence_status": "PROXY_NOT_EVIDENCE", "replacement_target": "actual inspection photo", "motion_relation": "inspection reveal"},
        {"shot_id": "S02", "viewport_id": "V02", "shot_type": "DETAIL", "asset_role": "material_detail", "subject": "外壁の質感を読むための近接面", "moment": "劣化サインを観察", "distance": "macro", "camera_angle": "neutral", "crop": "detail card", "information_purpose": "self diagnosis", "emotion": "attention", "evidence_status": "PROXY_NOT_EVIDENCE", "replacement_target": "actual crack / peeling photos", "motion_relation": "annotation reveal"},
        {"shot_id": "S03", "viewport_id": "V05", "shot_type": "PROCESS / DETAIL", "asset_role": "craft_handwork", "subject": "ローラーと手元", "moment": "準備と施工", "distance": "close", "camera_angle": "eye-level", "crop": "sticky process visual", "information_purpose": "process clarity", "emotion": "assurance", "evidence_status": "FREE_STOCK_CONTEXT", "replacement_target": "actual worker process photo", "motion_relation": "process progress"},
        {"shot_id": "S04", "viewport_id": "V04", "shot_type": "EXPLANATION", "asset_role": "vector_scope_drone", "subject": "屋根とドローン調査の関係図", "moment": "inspection", "distance": "diagram", "camera_angle": "orthographic", "crop": "full panel", "information_purpose": "quantified inspection proof", "emotion": "clarity", "evidence_status": "EXPLANATORY_PROXY", "replacement_target": "real drone inspection image", "motion_relation": "proof surface reveal"},
        {"shot_id": "S05", "viewport_id": "V07", "shot_type": "MATERIAL / DETAIL", "asset_role": "css_material_strip", "subject": "色見本と塗料性能の選択面", "moment": "choice", "distance": "macro", "camera_angle": "flat-lay", "crop": "horizontal strip", "information_purpose": "choice support", "emotion": "agency", "evidence_status": "ABSTRACT_NOT_REAL_COLOR", "replacement_target": "approved color material photography", "motion_relation": "material light pass"},
    ]
    motions = [
        {"motion_id": "M01", "trigger": "page_load", "intent": "ATTENTION + REVEAL", "from": "visual clipped to 18%", "to": "full inspection context", "duration": "1000ms", "easing": "cubic-bezier(.22,.61,.36,1)", "scroll_relation": "none", "desktop": "clip-path reveal", "mobile": "650–850ms", "reduced_motion": "final state immediately"},
        {"motion_id": "M02", "trigger": "viewport_entry", "intent": "EXPLANATION", "from": "leader line 0%", "to": "defect label connected", "duration": "420ms", "easing": "ease-out", "scroll_relation": "entry", "desktop": "staggered labels", "mobile": "tap/snap reveal", "reduced_motion": "visible"},
        {"motion_id": "M03", "trigger": "hover/focus/tap", "intent": "REVEAL", "from": "neutral scope map", "to": "wall/roof highlight", "duration": "260ms", "easing": "ease-out", "scroll_relation": "interaction", "desktop": "hover/focus", "mobile": "tap", "reduced_motion": "state change without transition"},
        {"motion_id": "M04", "trigger": "viewport_entry", "intent": "PROOF", "from": "masked metrics", "to": "aligned grid", "duration": "600ms", "easing": "ease-out", "scroll_relation": "entry", "desktop": "surface reveal", "mobile": "surface reveal", "reduced_motion": "visible"},
        {"motion_id": "M05", "trigger": "scroll", "intent": "PROCESS", "from": "step inactive", "to": "active image/step", "duration": "480ms", "easing": "ease-in-out", "scroll_relation": "sticky desktop / sequential mobile", "desktop": "sticky visual + progress", "mobile": "non-sticky sequence", "reduced_motion": "no auto movement"},
        {"motion_id": "M06", "trigger": "hover/focus", "intent": "ACTION", "from": "quiet link", "to": "small arrow/underline travel", "duration": "150ms", "easing": "ease-out", "scroll_relation": "none", "desktop": "underline", "mobile": "pressed state", "reduced_motion": "color only"},
    ]
    microcraft = {"minimum_decisions": 20, "decisions": ["hero location kicker", "01/09 index", "inspection rule", "asymmetric crop", "fact rail baseline", "DRONE SURVEY mono label", "detail leader line", "annotation dots", "image index", "scope legend", "metric source chip", "MAX superscript", "metric footnote", "process progress line", "active-step marker", "craft caption", "public-source link", "evidence source date", "color index", "screen-color disclaimer", "FAQ plus/minus", "phone availability", "CTA arrow 12–16px", "hover underline", "mobile sticky separator"]}
    mobile = {"primary_width": 390, "technical_widths": [320, 360, 375, 430], "global": "recomposed_not_desktop_stack", "V01": "brand/location → headline → image → lead → fact chips; 4:3 crop", "V02": "horizontal snap detail cards with 15% next-card edge", "V03": "full-width scope graphic then tap regions", "V04": "image first, 2×2 metrics", "V05": "sticky removed, image above active step", "V06": "single-column evidence cards with source labels", "V07": "horizontal material strip, no scroll hijack", "V08": "accordion, first item open", "V09": "full-width phone/form buttons plus sticky contact after hero; hidden at final", "spacing": {"hero_bottom": "56–72px", "major_section": "64–88px", "proof_separator": "40–56px"}}
    role_map = {"V01": ["kicker", "headline", "lead", "fact", "navigation cue"], "V02": ["kicker", "headline", "annotation", "body"], "V03": ["kicker", "headline", "scope label", "legend"], "V04": ["kicker", "headline", "lead", "metric", "caption", "footnote"], "V05": ["kicker", "headline", "lead", "step", "proof"], "V06": ["kicker", "headline", "lead", "proof card", "source"], "V07": ["kicker", "headline", "lead", "material", "footnote"], "V08": ["kicker", "headline", "question", "answer"], "V09": ["kicker", "headline", "lead", "CTA", "support"]}
    for viewport in experience["sections"]:
        viewport["copy_roles"] = role_map[viewport["viewport_id"]]
        viewport["visual_roles"] = [shot["shot_type"] for shot in shots if shot["viewport_id"] == viewport["viewport_id"]] or ["TYPOGRAPHY"]
        viewport["proof_roles"] = ["PUBLIC_FACT" if viewport["viewport_id"] in {"V04", "V06", "V08", "V09"} else "CONTEXT"]
        viewport["micro_craft"] = microcraft["decisions"][max(0, int(viewport["viewport_id"][1:]) - 1): int(viewport["viewport_id"][1:]) + 2]
        viewport["desktop_composition"] = {"grid": "12-column", "complete_idea": viewport["complete_idea"]}
        viewport["mobile_composition"] = {"mode": mobile.get(viewport["viewport_id"], "recomposed"), "complete_idea": viewport["complete_idea"]}
    return {"schema_version": "creative_composition_v2", "company_id": snapshot.get("company_id"), "copy": copy, "typography": typography, "shots": shots, "motion": motions, "microcraft": microcraft, "mobile": mobile, "asset_policy": {"new_assets": ["generated", "free_stock"], "actual_evidence_images": "HEARING_REQUIRED_BEFORE_USE", "proxy_never_evidence": True}, "viewport_bindings": experience["sections"]}
