"""Production Operations Contract for one LP project.

This module is intentionally provider-neutral and persistence-neutral.  It is
the backend contract that a future database, API, or operations UI can call.
The important invariants live here rather than in a dashboard:

* projects move only through declared, gated transitions;
* drafts and releases are separate, and releases are immutable snapshots;
* revisions create a new version and must be regenerated by the Engine;
* Safety, rights, QA, and human approval are never bypassed; and
* simulation/test records are visibly non-production.
"""

from __future__ import annotations

from copy import deepcopy
from dataclasses import asdict, dataclass, field
from datetime import UTC, datetime
import hashlib
import json
from typing import Any, Callable, Mapping
from uuid import uuid4


PROJECT_STATUSES = (
    "NEW",
    "RESEARCH_READY",
    "SALES_SAMPLE_GENERATING",
    "SALES_SAMPLE_READY",
    "HEARING_REQUIRED",
    "HEARING_IN_PROGRESS",
    "FINALIZATION_READY",
    "FINAL_GENERATING",
    "CLIENT_REVIEW",
    "REVISION_REQUIRED",
    "REVISION_GENERATING",
    "QA_REVIEW",
    "APPROVAL_REQUIRED",
    "RELEASE_CANDIDATE",
    "PUBLISH_READY",
    "DELIVERED",
    "ARCHIVED",
)

TRANSITIONS: dict[str, tuple[str, ...]] = {
    "NEW": ("RESEARCH_READY",),
    "RESEARCH_READY": ("SALES_SAMPLE_GENERATING",),
    "SALES_SAMPLE_GENERATING": ("SALES_SAMPLE_READY",),
    "SALES_SAMPLE_READY": ("HEARING_REQUIRED", "FINALIZATION_READY"),
    "HEARING_REQUIRED": ("HEARING_IN_PROGRESS",),
    "HEARING_IN_PROGRESS": ("FINALIZATION_READY",),
    "FINALIZATION_READY": ("FINAL_GENERATING",),
    "FINAL_GENERATING": ("CLIENT_REVIEW",),
    "CLIENT_REVIEW": ("REVISION_REQUIRED", "APPROVAL_REQUIRED"),
    "REVISION_REQUIRED": ("REVISION_GENERATING",),
    "REVISION_GENERATING": ("QA_REVIEW",),
    "QA_REVIEW": ("CLIENT_REVIEW", "APPROVAL_REQUIRED"),
    "APPROVAL_REQUIRED": ("RELEASE_CANDIDATE",),
    "RELEASE_CANDIDATE": ("PUBLISH_READY",),
    "PUBLISH_READY": ("DELIVERED",),
    "DELIVERED": ("ARCHIVED", "REVISION_REQUIRED"),
    "ARCHIVED": ("REVISION_REQUIRED",),
}

REVISION_TYPES = (
    "FACT_UPDATE",
    "COPY_PREFERENCE",
    "ASSET_REPLACEMENT",
    "DESIGN_PREFERENCE",
    "STRUCTURAL_CHANGE",
    "BUSINESS_CHANGE",
    "OUT_OF_SCOPE",
)

APPROVAL_TYPES = (
    "CONTENT_APPROVAL",
    "DESIGN_APPROVAL",
    "RIGHTS_APPROVAL",
    "RELEASE_APPROVAL",
)

ARTIFACT_TYPES = (
    "research_input",
    "evidence_ledger",
    "strategy",
    "IA",
    "copy",
    "art_direction",
    "render_spec",
    "HTML",
    "captures",
    "QA",
    "hearing_plan",
    "hearing_answers",
    "finalization_spec",
    "revision_request",
    "approval",
    "delivery_package",
)

EXCEPTION_STATUSES = (
    "WAITING_FOR_CLIENT",
    "WAITING_FOR_RIGHTS",
    "WAITING_FOR_DOCUMENT",
    "QA_FAILED",
    "SAFETY_BLOCKED",
    "APPROVAL_REQUIRED",
)


class OperationsError(RuntimeError):
    """Base error for an invariant violation in the operations contract."""


class IllegalTransitionError(OperationsError):
    """Raised when a project tries to skip or reverse a lifecycle state."""


class GateError(OperationsError):
    """Raised when a state transition's required evidence is not complete."""


class ImmutableReleaseError(OperationsError):
    """Raised when code attempts to edit a release instead of making a revision."""


def _now() -> str:
    return datetime.now(UTC).isoformat()


def _id(prefix: str) -> str:
    return f"{prefix}_{uuid4().hex[:12]}"


def _digest(value: Any) -> str:
    payload = json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return "sha256:" + hashlib.sha256(payload.encode("utf-8")).hexdigest()


@dataclass
class Project:
    project_id: str
    client_id: str
    company_id: str
    project_status: str = "NEW"
    current_version: str | None = None
    sales_sample_generation_id: str | None = None
    final_generation_id: str | None = None
    hearing_status: str = "NOT_STARTED"
    evidence_status: str = "INCOMPLETE"
    safety_status: str = "UNASSESSED"
    rights_status: str = "UNASSESSED"
    qa_status: str = "UNASSESSED"
    client_review_status: str = "NOT_STARTED"
    release_status: str = "NOT_READY"
    delivery_status: str = "NOT_DELIVERED"
    exception_status: str | None = None
    simulation_mode: bool = False
    rubric_version: str = "unknown"
    reviewer_contract_version: str = "unknown"
    active_release_id: str | None = None
    created_at: str = field(default_factory=_now)
    updated_at: str = field(default_factory=_now)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class ArtifactRecord:
    artifact_id: str
    project_id: str
    artifact_type: str
    path: str
    version_id: str | None = None
    generation_id: str | None = None
    content_digest: str | None = None
    immutable: bool = False
    metadata: dict[str, Any] = field(default_factory=dict)
    created_at: str = field(default_factory=_now)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class VersionManifest:
    version_id: str
    project_id: str
    parent_version: str | None
    generation_id: str | None
    label: str
    change_reason: str
    changed_inputs: list[str] = field(default_factory=list)
    changed_evidence: list[str] = field(default_factory=list)
    changed_sections: list[str] = field(default_factory=list)
    state: str = "DRAFT"
    created_at: str = field(default_factory=_now)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class RevisionRequest:
    revision_id: str
    project_id: str
    target_version: str
    request_text: str
    request_type: str
    affected_section: str = ""
    evidence_change: bool = False
    copy_change: bool = False
    visual_change: bool = False
    scope_change: bool = False
    safety_impact: str = "RECHECK_REQUIRED"
    rights_impact: str = "NO_CHANGE"
    priority: str = "NORMAL"
    status: str = "OPEN"
    created_at: str = field(default_factory=_now)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class ApprovalRecord:
    approval_id: str
    project_id: str
    version_id: str
    approval_scope: str
    approval_type: str
    approved_by: str
    approval_source: str
    approval_timestamp: str
    production_validity: str
    simulation_mode: bool = False

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class ReleaseManifest:
    release_id: str
    project_id: str
    version_id: str
    version: str
    evidence_snapshot: dict[str, Any]
    rights_snapshot: dict[str, Any]
    safety_result: dict[str, Any]
    qa_result: dict[str, Any]
    approval_result: list[dict[str, Any]]
    files: list[str]
    production_validity: str
    manifest_digest: str
    generated_at: str = field(default_factory=_now)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class DeliveryRecord:
    delivery_id: str
    project_id: str
    version: str
    delivery_method: str
    delivered_at: str
    status: str
    package_files: list[str] = field(default_factory=list)
    simulation_mode: bool = False

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class AuditEntry:
    audit_id: str
    project_id: str
    from_status: str | None
    to_status: str
    timestamp: str
    actor_type: str
    reason: str
    related_generation: str | None = None
    related_approval: str | None = None

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class NextAction:
    project_id: str
    required_action: str
    blocking_reason: str
    owner_role: str
    priority: str = "NORMAL"

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


class DeploymentAdapter:
    """Provider-neutral deployment boundary; Phase 4 only uses dry-run."""

    name = "provider-neutral"

    def prepare(self, release: Mapping[str, Any], *, dry_run: bool = True) -> dict[str, Any]:
        files = list(release.get("files", []))
        return {"status": "PREPARED", "dry_run": dry_run, "files": files, "adapter": self.name}

    def validate(self, package: Mapping[str, Any], *, dry_run: bool = True) -> dict[str, Any]:
        issues = []
        if not package.get("files"):
            issues.append("publish package has no files")
        if not package.get("manifest_digest"):
            issues.append("publish package has no manifest digest")
        return {"status": "PASS" if not issues else "FAIL", "dry_run": dry_run, "issues": issues}

    def publish(self, package: Mapping[str, Any], *, dry_run: bool = True) -> dict[str, Any]:
        if not dry_run:
            raise OperationsError("external publish is disabled in Phase 4")
        return {"status": "DRY_RUN", "published": False, "package_digest": package.get("manifest_digest")}

    def verify(self, publication: Mapping[str, Any], *, dry_run: bool = True) -> dict[str, Any]:
        return {"status": "PASS", "dry_run": dry_run, "external_change": False}

    def rollback(self, release: Mapping[str, Any], *, dry_run: bool = True) -> dict[str, Any]:
        return {"status": "DRY_RUN" if dry_run else "BLOCKED", "dry_run": dry_run, "release_id": release.get("release_id")}


def classify_revision(request_text: str, requested_type: str | None = None) -> dict[str, Any]:
    """Classify a client request into a structured, safety-aware change."""
    text = str(request_text).strip()
    if not text:
        raise ValueError("revision request text is required")
    if requested_type and requested_type not in REVISION_TYPES:
        raise ValueError(f"unsupported revision type: {requested_type}")
    lower = text.lower()
    claim_markers = ("no.1", "no1", "ナンバーワン", "日本一", "業界一", "最安", "必ず", "絶対")
    asset_markers = ("写真", "画像", "ロゴ", "素材", "photo", "image", "asset")
    structural_markers = ("追加", "削除", "セクション", "構成", "ページ")
    business_markers = ("料金", "価格", "営業時間", "サービス", "メニュー", "予約")
    if requested_type:
        request_type = requested_type
    elif any(marker in lower for marker in claim_markers):
        request_type = "FACT_UPDATE"
    elif any(marker in lower for marker in asset_markers):
        request_type = "ASSET_REPLACEMENT"
    elif any(marker in text for marker in structural_markers):
        request_type = "STRUCTURAL_CHANGE"
    elif any(marker in text for marker in business_markers):
        request_type = "BUSINESS_CHANGE"
    else:
        request_type = "COPY_PREFERENCE"
    evidence_change = request_type in {"FACT_UPDATE", "BUSINESS_CHANGE"} or any(marker in lower for marker in claim_markers)
    visual_change = request_type in {"ASSET_REPLACEMENT", "DESIGN_PREFERENCE"}
    scope_change = request_type in {"STRUCTURAL_CHANGE", "OUT_OF_SCOPE"}
    safety_impact = "BLOCKED_PENDING_EVIDENCE" if any(marker in lower for marker in claim_markers) else "RECHECK_REQUIRED"
    rights_impact = "RIGHTS_RECHECK_REQUIRED" if visual_change else "NO_CHANGE"
    return {
        "request_type": request_type,
        "evidence_change": evidence_change,
        "copy_change": request_type in {"COPY_PREFERENCE", "FACT_UPDATE", "BUSINESS_CHANGE"},
        "visual_change": visual_change,
        "scope_change": scope_change,
        "safety_impact": safety_impact,
        "rights_impact": rights_impact,
    }


class OperationsStore:
    """In-memory reference implementation of the Production Operations Contract."""

    def __init__(self, *, clock: Callable[[], str] | None = None, deployment: DeploymentAdapter | None = None):
        self.clock = clock or _now
        self.deployment = deployment or DeploymentAdapter()
        self.projects: dict[str, Project] = {}
        self.artifacts: dict[str, ArtifactRecord] = {}
        self.versions: dict[str, VersionManifest] = {}
        self.revisions: dict[str, RevisionRequest] = {}
        self.approvals: dict[str, ApprovalRecord] = {}
        self.releases: dict[str, ReleaseManifest] = {}
        self.deliveries: dict[str, DeliveryRecord] = {}
        self.audit_log: list[AuditEntry] = []
        self.next_actions: dict[str, NextAction] = {}
        self.publish_packages: dict[str, dict[str, Any]] = {}
        self.rollback_history: list[dict[str, Any]] = []

    def _touch(self, project: Project) -> None:
        project.updated_at = self.clock()

    def create_project(
        self,
        *,
        project_id: str,
        client_id: str,
        company_id: str,
        simulation_mode: bool = False,
        rubric_version: str = "unknown",
        reviewer_contract_version: str = "unknown",
    ) -> Project:
        if project_id in self.projects:
            return deepcopy(self.projects[project_id])
        project = Project(
            project_id=project_id,
            client_id=client_id,
            company_id=company_id,
            simulation_mode=simulation_mode,
            rubric_version=rubric_version,
            reviewer_contract_version=reviewer_contract_version,
            created_at=self.clock(),
            updated_at=self.clock(),
        )
        self.projects[project_id] = project
        self._audit(project, None, "NEW", "Project created", actor_type="SYSTEM")
        return deepcopy(project)

    def get_project(self, project_id: str) -> Project:
        try:
            return deepcopy(self.projects[project_id])
        except KeyError as exc:
            raise OperationsError(f"unknown project: {project_id}") from exc

    def get_release(self, release_id: str) -> ReleaseManifest:
        try:
            return deepcopy(self.releases[release_id])
        except KeyError as exc:
            raise OperationsError(f"unknown release: {release_id}") from exc

    def update_release(self, release_id: str, **changes: Any) -> None:
        """Explicitly reject direct release edits; use a revision instead."""
        if release_id not in self.releases:
            raise OperationsError(f"unknown release: {release_id}")
        raise ImmutableReleaseError("released versions are immutable; create a structured revision")

    def _project(self, project_id: str) -> Project:
        if project_id not in self.projects:
            raise OperationsError(f"unknown project: {project_id}")
        return self.projects[project_id]

    def _audit(
        self,
        project: Project,
        from_status: str | None,
        to_status: str,
        reason: str,
        *,
        actor_type: str = "SYSTEM",
        related_generation: str | None = None,
        related_approval: str | None = None,
    ) -> None:
        self.audit_log.append(AuditEntry(
            audit_id=_id("audit"),
            project_id=project.project_id,
            from_status=from_status,
            to_status=to_status,
            timestamp=self.clock(),
            actor_type=actor_type,
            reason=reason,
            related_generation=related_generation,
            related_approval=related_approval,
        ))

    def _gate(self, project: Project, target: str, context: Mapping[str, Any] | None = None) -> None:
        context = context or {}
        if target not in PROJECT_STATUSES:
            raise IllegalTransitionError(f"unknown project status: {target}")
        current = project.project_status
        if target not in TRANSITIONS.get(current, ()):
            raise IllegalTransitionError(f"illegal transition: {current} -> {target}")
        checks: dict[str, tuple[bool, str]] = {
            "RESEARCH_READY": (self._has_artifact(project.project_id, "research_input"), "research input artifact is required"),
            "SALES_SAMPLE_GENERATING": (self._has_artifact(project.project_id, "research_input"), "research input artifact is required"),
            "SALES_SAMPLE_READY": (bool(project.sales_sample_generation_id), "sales sample generation is required"),
            "HEARING_REQUIRED": (project.hearing_status in {"REQUIRED", "INCOMPLETE"}, "hearing is not required or has no recorded gap"),
            "HEARING_IN_PROGRESS": (self._has_artifact(project.project_id, "hearing_plan"), "hearing plan artifact is required"),
            "FINALIZATION_READY": (
                project.evidence_status == "COMPLETE" and project.safety_status == "PASS" and project.rights_status == "PASS",
                "evidence, safety, and rights must all be PASS/COMPLETE",
            ),
            "FINAL_GENERATING": (True, ""),
            "CLIENT_REVIEW": (bool(project.final_generation_id), "final generation is required"),
            "REVISION_REQUIRED": (bool(context.get("revision_id")), "revision request is required"),
            "REVISION_GENERATING": (bool(context.get("revision_id")), "revision request is required"),
            "QA_REVIEW": (bool(project.final_generation_id), "regenerated version is required"),
            "APPROVAL_REQUIRED": (project.qa_status == "PASS" and project.client_review_status in {"APPROVED", "APPROVED_SIMULATED"}, "QA must PASS and client review approval must be recorded"),
            "RELEASE_CANDIDATE": (self._all_approvals(project), "all four approvals are required"),
            "PUBLISH_READY": (project.release_status == "RELEASE_CANDIDATE", "release candidate is required"),
            "DELIVERED": (project.release_status == "PUBLISH_READY" and bool(context.get("delivery_id")), "publish-ready package and delivery record are required"),
            "ARCHIVED": (project.delivery_status == "DELIVERED", "delivery must be recorded"),
        }
        ok, reason = checks.get(target, (True, ""))
        if not ok:
            raise GateError(f"{target} blocked: {reason}")

    def transition(
        self,
        project_id: str,
        target: str,
        *,
        reason: str,
        actor_type: str = "SYSTEM",
        context: Mapping[str, Any] | None = None,
        related_generation: str | None = None,
        related_approval: str | None = None,
    ) -> Project:
        project = self._project(project_id)
        self._gate(project, target, context)
        previous = project.project_status
        project.project_status = target
        self._touch(project)
        self._audit(project, previous, target, reason, actor_type=actor_type, related_generation=related_generation, related_approval=related_approval)
        return deepcopy(project)

    def _has_artifact(self, project_id: str, artifact_type: str) -> bool:
        return any(a.project_id == project_id and a.artifact_type == artifact_type for a in self.artifacts.values())

    def register_artifact(
        self,
        project_id: str,
        artifact_type: str,
        path: str,
        *,
        version_id: str | None = None,
        generation_id: str | None = None,
        content: Any = None,
        metadata: Mapping[str, Any] | None = None,
        immutable: bool = False,
    ) -> ArtifactRecord:
        project = self._project(project_id)
        if artifact_type not in ARTIFACT_TYPES:
            raise ValueError(f"unsupported artifact type: {artifact_type}")
        key = (project_id, artifact_type, path, version_id, generation_id)
        for existing in self.artifacts.values():
            if (existing.project_id, existing.artifact_type, existing.path, existing.version_id, existing.generation_id) == key:
                return deepcopy(existing)
        record = ArtifactRecord(
            artifact_id=_id("artifact"),
            project_id=project_id,
            artifact_type=artifact_type,
            path=path,
            version_id=version_id,
            generation_id=generation_id,
            content_digest=_digest(content) if content is not None else None,
            immutable=immutable,
            metadata=dict(metadata or {}),
            created_at=self.clock(),
        )
        self.artifacts[record.artifact_id] = record
        self._touch(project)
        return deepcopy(record)

    def create_version(
        self,
        project_id: str,
        *,
        label: str,
        change_reason: str,
        generation_id: str | None = None,
        changed_inputs: list[str] | None = None,
        changed_evidence: list[str] | None = None,
        changed_sections: list[str] | None = None,
    ) -> VersionManifest:
        project = self._project(project_id)
        parent = project.current_version
        version = VersionManifest(
            version_id=_id("version"),
            project_id=project_id,
            parent_version=parent,
            generation_id=generation_id,
            label=label,
            change_reason=change_reason,
            changed_inputs=list(changed_inputs or []),
            changed_evidence=list(changed_evidence or []),
            changed_sections=list(changed_sections or []),
            created_at=self.clock(),
        )
        self.versions[version.version_id] = version
        project.current_version = version.version_id
        self._touch(project)
        return deepcopy(version)

    def register_research_input(self, project_id: str, path: str, *, content: Any = None) -> ArtifactRecord:
        return self.register_artifact(project_id, "research_input", path, content=content)

    def start_sales_sample(self, project_id: str, *, reason: str = "Sales sample generation started") -> Project:
        return self.transition(project_id, "SALES_SAMPLE_GENERATING", reason=reason)

    def complete_sales_sample(self, project_id: str, generation_id: str, output_path: str, *, qa_status: str = "PASS") -> Project:
        project = self._project(project_id)
        project.sales_sample_generation_id = generation_id
        project.hearing_status = "REQUIRED"
        project.qa_status = qa_status
        self.register_artifact(project_id, "HTML", output_path, generation_id=generation_id)
        self._touch(project)
        return self.transition(project_id, "SALES_SAMPLE_READY", reason="Sales sample generation completed", related_generation=generation_id)

    def set_hearing_plan(self, project_id: str, path: str, *, required: bool = True, content: Any = None) -> ArtifactRecord:
        project = self._project(project_id)
        project.hearing_status = "REQUIRED" if required else "NOT_REQUIRED"
        self._touch(project)
        return self.register_artifact(project_id, "hearing_plan", path, content=content)

    def start_hearing(self, project_id: str) -> Project:
        return self.transition(project_id, "HEARING_IN_PROGRESS", reason="Client hearing started", actor_type="OPERATOR")

    def complete_evidence(
        self,
        project_id: str,
        *,
        evidence_path: str,
        safety_status: str,
        rights_status: str,
        content: Any = None,
        hearing_answers_path: str | None = None,
    ) -> Project:
        project = self._project(project_id)
        project.evidence_status = "COMPLETE" if safety_status == "PASS" and rights_status == "PASS" else "INCOMPLETE"
        project.safety_status = safety_status
        project.rights_status = rights_status
        project.hearing_status = "COMPLETE" if project.evidence_status == "COMPLETE" else "INCOMPLETE"
        if safety_status != "PASS":
            project.exception_status = "SAFETY_BLOCKED"
        elif rights_status != "PASS":
            project.exception_status = "WAITING_FOR_RIGHTS"
        self.register_artifact(project_id, "evidence_ledger", evidence_path, content=content)
        if hearing_answers_path:
            self.register_artifact(project_id, "hearing_answers", hearing_answers_path)
        self._touch(project)
        return deepcopy(project)

    def mark_finalization_ready(self, project_id: str) -> Project:
        project = self._project(project_id)
        return self.transition(project_id, "FINALIZATION_READY", reason="Evidence, rights, and Safety gates complete")

    def start_final_generation(self, project_id: str, *, reason: str = "Final generation started") -> Project:
        return self.transition(project_id, "FINAL_GENERATING", reason=reason)

    def complete_generation(
        self,
        project_id: str,
        generation_id: str,
        output_path: str,
        *,
        version_label: str,
        change_reason: str,
        is_revision: bool = False,
        changed_inputs: list[str] | None = None,
        changed_evidence: list[str] | None = None,
        changed_sections: list[str] | None = None,
    ) -> VersionManifest:
        project = self._project(project_id)
        version = self.create_version(
            project_id,
            label=version_label,
            change_reason=change_reason,
            generation_id=generation_id,
            changed_inputs=changed_inputs,
            changed_evidence=changed_evidence,
            changed_sections=changed_sections,
        )
        self.versions[version.version_id].state = "DRAFT"
        self.register_artifact(project_id, "HTML", output_path, version_id=version.version_id, generation_id=generation_id)
        project.final_generation_id = generation_id
        self._touch(project)
        return deepcopy(version)

    def move_to_client_review(self, project_id: str) -> Project:
        return self.transition(project_id, "CLIENT_REVIEW", reason="Generated version prepared for client review", related_generation=self._project(project_id).final_generation_id)

    def submit_client_review(self, project_id: str, *, approved: bool, reason: str = "Client review recorded", simulation_mode: bool | None = None) -> Project:
        project = self._project(project_id)
        simulated = project.simulation_mode if simulation_mode is None else simulation_mode
        if not approved:
            project.client_review_status = "REVISION_REQUIRED"
            self._touch(project)
            revision = self.request_revision(project_id, target_version=project.current_version or "", request_text=reason, requested_type="COPY_PREFERENCE")
            return self.transition(project_id, "REVISION_REQUIRED", reason=reason, actor_type="SIMULATED_CLIENT" if simulated else "CLIENT", context={"revision_id": revision.revision_id})
        project.client_review_status = "APPROVED_SIMULATED" if simulated else "APPROVED"
        project.exception_status = None
        self._touch(project)
        return self.transition(project_id, "APPROVAL_REQUIRED", reason=reason, actor_type="SIMULATED_CLIENT" if simulated else "CLIENT")

    def request_revision(
        self,
        project_id: str,
        *,
        target_version: str,
        request_text: str,
        requested_type: str | None = None,
        affected_section: str = "",
        priority: str = "NORMAL",
    ) -> RevisionRequest:
        project = self._project(project_id)
        target_version = target_version or project.current_version or ""
        if not target_version:
            raise OperationsError("revision requires a target version")
        if target_version not in self.versions and target_version != "":
            raise OperationsError(f"unknown target version: {target_version}")
        classification = classify_revision(request_text, requested_type)
        revision = RevisionRequest(
            revision_id=_id("revision"),
            project_id=project_id,
            target_version=target_version,
            request_text=request_text,
            request_type=classification["request_type"],
            affected_section=affected_section,
            evidence_change=classification["evidence_change"],
            copy_change=classification["copy_change"],
            visual_change=classification["visual_change"],
            scope_change=classification["scope_change"],
            safety_impact=classification["safety_impact"],
            rights_impact=classification["rights_impact"],
            priority=priority,
            created_at=self.clock(),
        )
        self.revisions[revision.revision_id] = revision
        self.register_artifact(project_id, "revision_request", f"revisions/{revision.revision_id}.json", content=revision.to_dict())
        return deepcopy(revision)

    def start_revision(self, project_id: str, revision_id: str) -> Project:
        project = self._project(project_id)
        revision = self.revisions.get(revision_id)
        if not revision or revision.project_id != project_id:
            raise OperationsError("revision does not belong to project")
        if revision.safety_impact == "BLOCKED_PENDING_EVIDENCE":
            project.exception_status = "SAFETY_BLOCKED"
            self._touch(project)
            raise GateError("revision is blocked until supporting evidence is verified")
        if revision.rights_impact == "RIGHTS_RECHECK_REQUIRED" and project.rights_status != "PASS":
            project.exception_status = "WAITING_FOR_RIGHTS"
            self._touch(project)
            raise GateError("asset revision is blocked until rights are cleared")
        revision.status = "IN_PROGRESS"
        self._touch(project)
        return self.transition(project_id, "REVISION_GENERATING", reason="Structured revision accepted for Engine regeneration", actor_type="OPERATOR", context={"revision_id": revision_id})

    def regenerate_revision(
        self,
        project_id: str,
        revision_id: str,
        *,
        input_data: Mapping[str, Any],
        output_dir: str,
        runner: Callable[..., Any],
        generation_id: str,
        mode: str = "production",
    ) -> VersionManifest:
        project = self._project(project_id)
        revision = self.revisions.get(revision_id)
        if not revision or revision.project_id != project_id or revision.status != "IN_PROGRESS":
            raise OperationsError("revision is not ready for regeneration")
        if revision.safety_impact == "BLOCKED_PENDING_EVIDENCE":
            raise GateError("Safety-blocked revision cannot be regenerated")
        result = runner(input_data, output_dir, generation_id=generation_id, mode=mode)
        manifest = getattr(result, "manifest", {}) or {}
        safety = getattr(result, "safety_report", {}) or {}
        if mode == "production" and not getattr(result, "production_output_allowed", False):
            raise GateError("Engine did not produce a production-approved revision")
        version = self.complete_generation(
            project_id,
            generation_id,
            output_dir,
            version_label=f"v{self._next_version_number(project_id)} Revision",
            change_reason=revision.request_text,
            is_revision=True,
            changed_inputs=[revision.revision_id],
            changed_evidence=[revision.revision_id] if revision.evidence_change else [],
            changed_sections=[revision.affected_section] if revision.affected_section else [],
        )
        self.register_artifact(project_id, "render_spec", f"{output_dir}/render_spec.json", version_id=version.version_id, generation_id=generation_id, metadata={"engine_manifest": manifest})
        self.register_artifact(project_id, "QA", f"{output_dir}/qa_report.json", version_id=version.version_id, generation_id=generation_id, metadata={"safety": safety})
        revision.status = "REGENERATED"
        project.safety_status = "PASS" if safety.get("safety_status", "PASS") == "PASS" else safety.get("safety_status", "FAIL")
        project.qa_status = "UNASSESSED"
        project.exception_status = None
        self._touch(project)
        return version

    def record_qa(self, project_id: str, *, status: str, report_path: str, checks: Mapping[str, Any] | None = None) -> Project:
        project = self._project(project_id)
        normalized = str(status).upper()
        if normalized not in {"PASS", "FAIL"}:
            raise ValueError("QA status must be PASS or FAIL")
        project.qa_status = normalized
        project.exception_status = None if normalized == "PASS" else "QA_FAILED"
        self.register_artifact(project_id, "QA", report_path, version_id=project.current_version, generation_id=project.final_generation_id, content=checks)
        self._touch(project)
        return deepcopy(project)

    def complete_qa(self, project_id: str, *, status: str, report_path: str, return_to_client: bool = True) -> Project:
        self.record_qa(project_id, status=status, report_path=report_path)
        project = self._project(project_id)
        if project.project_status == "REVISION_GENERATING":
            project = self.transition(project_id, "QA_REVIEW", reason="Revision output submitted to QA", related_generation=project.final_generation_id)
        if str(status).upper() != "PASS":
            return deepcopy(self._project(project_id))
        target = "CLIENT_REVIEW" if return_to_client else "APPROVAL_REQUIRED"
        return self.transition(project_id, target, reason="Revision QA completed", related_generation=project.final_generation_id)

    def _all_approvals(self, project: Project) -> bool:
        if not project.current_version:
            return False
        found = {a.approval_type for a in self.approvals.values() if a.project_id == project.project_id and a.version_id == project.current_version}
        return set(APPROVAL_TYPES).issubset(found)

    def record_approval(
        self,
        project_id: str,
        *,
        version_id: str,
        approval_type: str,
        approval_scope: str,
        approved_by: str,
        approval_source: str,
        production_validity: str,
        approval_id: str | None = None,
        simulation_mode: bool = False,
    ) -> ApprovalRecord:
        project = self._project(project_id)
        if approval_type not in APPROVAL_TYPES:
            raise ValueError(f"unsupported approval type: {approval_type}")
        if version_id != project.current_version:
            raise GateError("approval must target the current draft version")
        if simulation_mode and not project.simulation_mode:
            raise GateError("simulated approval cannot be attached to a real project")
        if not simulation_mode and approval_source.upper().startswith("SIMULATED"):
            raise GateError("fake client approval is forbidden")
        for existing in self.approvals.values():
            if existing.project_id == project_id and existing.version_id == version_id and existing.approval_type == approval_type:
                return deepcopy(existing)
        approval = ApprovalRecord(
            approval_id=approval_id or _id("approval"),
            project_id=project_id,
            version_id=version_id,
            approval_scope=approval_scope,
            approval_type=approval_type,
            approved_by=approved_by,
            approval_source=approval_source,
            approval_timestamp=self.clock(),
            production_validity=production_validity,
            simulation_mode=simulation_mode,
        )
        self.approvals[approval.approval_id] = approval
        self.register_artifact(project_id, "approval", f"approvals/{approval.approval_id}.json", version_id=version_id, immutable=True, content=approval.to_dict())
        self._touch(project)
        return deepcopy(approval)

    def create_release_candidate(self, project_id: str, *, files: list[str], evidence_snapshot: Mapping[str, Any], rights_snapshot: Mapping[str, Any], safety_result: Mapping[str, Any], qa_result: Mapping[str, Any]) -> ReleaseManifest:
        project = self._project(project_id)
        if project.project_status != "APPROVAL_REQUIRED":
            raise IllegalTransitionError("release candidate can only be created from APPROVAL_REQUIRED")
        if not self._all_approvals(project):
            raise GateError("all approvals are required before release")
        if project.qa_status != "PASS" or project.safety_status != "PASS" or project.rights_status != "PASS":
            raise GateError("QA, Safety, and Rights must all PASS before release")
        approvals = [a.to_dict() for a in self.approvals.values() if a.project_id == project_id and a.version_id == project.current_version]
        payload = {
            "evidence_snapshot": deepcopy(dict(evidence_snapshot)),
            "rights_snapshot": deepcopy(dict(rights_snapshot)),
            "safety_result": deepcopy(dict(safety_result)),
            "qa_result": deepcopy(dict(qa_result)),
            "approval_result": deepcopy(approvals),
            "files": list(files),
        }
        validity = "SIMULATED_TEST_ONLY" if project.simulation_mode else "PRODUCTION_APPROVED"
        release = ReleaseManifest(
            release_id=_id("release"),
            project_id=project_id,
            version_id=project.current_version or "",
            version=self.versions[project.current_version].label,
            **payload,
            production_validity=validity,
            manifest_digest=_digest(payload),
            generated_at=self.clock(),
        )
        self.releases[release.release_id] = release
        self.versions[release.version_id].state = "RELEASED"
        self.register_artifact(project_id, "delivery_package", f"releases/{release.release_id}/manifest.json", version_id=release.version_id, immutable=True, content=release.to_dict())
        project.release_status = "RELEASE_CANDIDATE"
        project.active_release_id = release.release_id
        self._touch(project)
        self.transition(project_id, "RELEASE_CANDIDATE", reason="All approvals and QA gates complete", related_approval=approvals[-1]["approval_id"] if approvals else None)
        return deepcopy(release)

    def prepare_publish(self, project_id: str, *, dry_run: bool = True) -> dict[str, Any]:
        project = self._project(project_id)
        if project.project_status != "RELEASE_CANDIDATE" or not project.active_release_id:
            raise GateError("publish preparation requires a release candidate")
        release = self.releases[project.active_release_id]
        prepared = self.deployment.prepare(release.to_dict(), dry_run=dry_run)
        package = {**prepared, "manifest_digest": release.manifest_digest, "release_id": release.release_id, "files": list(release.files)}
        validation = self.deployment.validate(package, dry_run=dry_run)
        if validation["status"] != "PASS":
            raise GateError("publish package validation failed: " + "; ".join(validation["issues"]))
        publication = self.deployment.publish(package, dry_run=dry_run)
        verification = self.deployment.verify(publication, dry_run=dry_run)
        package.update({"validation": validation, "publication": publication, "verification": verification, "dry_run": dry_run})
        self.publish_packages[release.release_id] = deepcopy(package)
        self.transition(project_id, "PUBLISH_READY", reason="Provider-neutral publish package validated (dry run)")
        project.release_status = "PUBLISH_READY"
        self._touch(project)
        return deepcopy(package)

    def deliver(self, project_id: str, *, delivery_method: str = "PACKAGE", package_files: list[str] | None = None, delivery_id: str | None = None) -> DeliveryRecord:
        project = self._project(project_id)
        if project.project_status != "PUBLISH_READY" or not project.active_release_id:
            raise GateError("delivery requires PUBLISH_READY")
        for existing in self.deliveries.values():
            if existing.project_id == project_id and existing.version == self.releases[project.active_release_id].version:
                return deepcopy(existing)
        release = self.releases[project.active_release_id]
        record = DeliveryRecord(
            delivery_id=delivery_id or _id("delivery"),
            project_id=project_id,
            version=release.version,
            delivery_method=delivery_method,
            delivered_at=self.clock(),
            status="DELIVERED_SIMULATED" if project.simulation_mode else "DELIVERED",
            package_files=list(package_files or release.files),
            simulation_mode=project.simulation_mode,
        )
        self.deliveries[record.delivery_id] = record
        project.delivery_status = "DELIVERED"
        self._touch(project)
        self.transition(project_id, "DELIVERED", reason="Release package delivered", context={"delivery_id": record.delivery_id})
        return deepcopy(record)

    def archive(self, project_id: str) -> Project:
        return self.transition(project_id, "ARCHIVED", reason="Delivery archived with immutable evidence, rights, QA, and approval snapshots")

    def rollback(self, project_id: str, *, target_release_id: str, reason: str = "Rollback requested", dry_run: bool = True) -> dict[str, Any]:
        project = self._project(project_id)
        if project.project_status not in {"DELIVERED", "PUBLISH_READY", "ARCHIVED"}:
            raise GateError("rollback requires a delivered or publish-ready release")
        target = self.releases.get(target_release_id)
        if not target or target.project_id != project_id or target_release_id == project.active_release_id:
            raise GateError("rollback target release does not exist for project")
        approved_releases = [release for release in self.releases.values() if release.project_id == project_id and release.production_validity in {"PRODUCTION_APPROVED", "SIMULATED_TEST_ONLY"}]
        if len(approved_releases) < 2:
            raise GateError("rollback requires a previous approved release")
        if target.production_validity not in {"PRODUCTION_APPROVED", "SIMULATED_TEST_ONLY"}:
            raise GateError("rollback target is not approved")
        result = self.deployment.rollback(target.to_dict(), dry_run=dry_run)
        if result["status"] not in {"DRY_RUN", "PASS"}:
            raise GateError("rollback adapter rejected target release")
        record = {
            "rollback_id": _id("rollback"),
            "project_id": project_id,
            "from_release_id": project.active_release_id,
            "to_release_id": target_release_id,
            "target_version": target.version,
            "reason": reason,
            "dry_run": dry_run,
            "safety_status": target.safety_result.get("safety_status", project.safety_status),
            "manifest_digest": target.manifest_digest,
            "timestamp": self.clock(),
        }
        self.rollback_history.append(record)
        project.active_release_id = target_release_id
        self._touch(project)
        self._audit(project, project.project_status, project.project_status, reason, actor_type="OPERATOR", related_generation=target.version_id)
        return deepcopy(record)

    def next_action(self, project_id: str) -> NextAction:
        project = self._project(project_id)
        if project.exception_status:
            mapping = {
                "WAITING_FOR_CLIENT": ("COLLECT_CLIENT_INPUT", "client response is required", "CS"),
                "WAITING_FOR_RIGHTS": ("COLLECT_RIGHTS_CONFIRMATION", "asset rights are unresolved", "CS"),
                "WAITING_FOR_DOCUMENT": ("COLLECT_SUPPORTING_DOCUMENT", "supporting document is required", "CS"),
                "QA_FAILED": ("FIX_QA_FAILURE", "QA failed; release is blocked", "QA"),
                "SAFETY_BLOCKED": ("RESOLVE_SAFETY_BLOCK", "Safety gate is blocking progress", "SAFETY"),
                "APPROVAL_REQUIRED": ("COLLECT_APPROVALS", "client and release approvals are incomplete", "ACCOUNT_OWNER"),
            }
            action, reason, owner = mapping[project.exception_status]
        else:
            mapping = {
                "NEW": ("REGISTER_RESEARCH_INPUT", "research input is missing", "RESEARCH"),
                "RESEARCH_READY": ("START_SALES_SAMPLE", "sales sample has not started", "CREATIVE"),
                "SALES_SAMPLE_GENERATING": ("COMPLETE_SALES_SAMPLE", "sales sample generation is in progress", "CREATIVE"),
                "SALES_SAMPLE_READY": ("START_HEARING", "client evidence gap plan is required", "CS"),
                "HEARING_REQUIRED": ("START_HEARING", "client evidence is required", "CS"),
                "HEARING_IN_PROGRESS": ("COMPLETE_EVIDENCE", "verification, provenance, and rights are pending", "CS"),
                "FINALIZATION_READY": ("START_FINAL_GENERATION", "final generation is ready", "CREATIVE"),
                "FINAL_GENERATING": ("COMPLETE_FINAL_GENERATION", "final generation is in progress", "CREATIVE"),
                "CLIENT_REVIEW": ("COLLECT_CLIENT_REVIEW", "client review is pending", "ACCOUNT_OWNER"),
                "REVISION_REQUIRED": ("START_REVISION", "structured revision request is open", "CREATIVE"),
                "REVISION_GENERATING": ("COMPLETE_REVISION_GENERATION", "revision regeneration is in progress", "CREATIVE"),
                "QA_REVIEW": ("RUN_QA", "revision QA is required", "QA"),
                "APPROVAL_REQUIRED": ("COLLECT_APPROVALS", "approval contract is incomplete", "ACCOUNT_OWNER"),
                "RELEASE_CANDIDATE": ("PREPARE_PUBLISH", "publish package dry run is pending", "RELEASE"),
                "PUBLISH_READY": ("DELIVER_PACKAGE", "delivery is pending", "DELIVERY"),
                "DELIVERED": ("ARCHIVE_PROJECT", "archive is pending", "OPERATIONS"),
                "ARCHIVED": ("NONE", "project lifecycle is complete", "OPERATIONS"),
            }
            action, reason, owner = mapping[project.project_status]
        action_record = NextAction(project_id, action, reason, owner, "HIGH" if project.exception_status else "NORMAL")
        self.next_actions[project_id] = action_record
        return deepcopy(action_record)

    def advance_project(self, project_id: str) -> dict[str, Any]:
        """Advance only safe, non-human states; never auto-approve or publish."""
        project = self._project(project_id)
        advanced: list[str] = []
        while True:
            current = project.project_status
            if current == "NEW" and self._has_artifact(project_id, "research_input"):
                project = self.transition(project_id, "RESEARCH_READY", reason="Research input gate satisfied")
            elif current == "RESEARCH_READY" and self._has_artifact(project_id, "research_input"):
                project = self.transition(project_id, "SALES_SAMPLE_GENERATING", reason="Sales sample queued")
            elif current == "SALES_SAMPLE_GENERATING" and project.sales_sample_generation_id:
                project = self.transition(project_id, "SALES_SAMPLE_READY", reason="Sales sample available", related_generation=project.sales_sample_generation_id)
            elif current == "HEARING_REQUIRED" and self._has_artifact(project_id, "hearing_plan"):
                break
            elif current == "FINALIZATION_READY":
                break
            elif current in {"CLIENT_REVIEW", "APPROVAL_REQUIRED", "RELEASE_CANDIDATE", "PUBLISH_READY", "DELIVERED", "ARCHIVED"}:
                break
            else:
                break
            advanced.append(project.project_status)
        return {"project_id": project_id, "advanced": advanced, "current_status": project.project_status, "next_action": self.next_action(project_id).to_dict()}

    def export(self) -> dict[str, Any]:
        return {
            "projects": [p.to_dict() for p in self.projects.values()],
            "artifacts": [a.to_dict() for a in self.artifacts.values()],
            "versions": [v.to_dict() for v in self.versions.values()],
            "revisions": [r.to_dict() for r in self.revisions.values()],
            "approvals": [a.to_dict() for a in self.approvals.values()],
            "releases": [r.to_dict() for r in self.releases.values()],
            "deliveries": [d.to_dict() for d in self.deliveries.values()],
            "audit_log": [a.to_dict() for a in self.audit_log],
            "next_actions": [a.to_dict() for a in self.next_actions.values()],
            "publish_packages": deepcopy(self.publish_packages),
            "rollback_history": deepcopy(self.rollback_history),
        }

    def _next_version_number(self, project_id: str) -> int:
        return sum(1 for version in self.versions.values() if version.project_id == project_id) + 1


__all__ = [
    "APPROVAL_TYPES",
    "ARTIFACT_TYPES",
    "DeploymentAdapter",
    "EXCEPTION_STATUSES",
    "GateError",
    "IllegalTransitionError",
    "ImmutableReleaseError",
    "OperationsError",
    "OperationsStore",
    "PROJECT_STATUSES",
    "REVISION_TYPES",
    "TRANSITIONS",
    "classify_revision",
]
