"""Round 2J: Nagi Quality Ceiling Prototype Implementation.

This runner composes a Human Cinema prototype on top of the proven Round 2H-H
Floor Engine.  It intentionally keeps the fact, safety, browser, and line QA
contracts while adding a company-specific Ceiling Director instance.
"""
from __future__ import annotations

import asyncio
import html
import importlib.util
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
from lp_engine.browser_qa import DEFAULT_WIDTHS, run_browser_qa_sync, run_rendered_line_qa
from lp_engine.ceiling_director import CEILING_CONTRACT_FIELDS, validate_ceiling_director_contract
from lp_engine.sales_sample_policy import DerivedCopyRecord, classify_public_facts, provisional_propagation_gate, replacement_manifest


def load_h_runner():
    spec = importlib.util.spec_from_file_location("round2h_h_nagi", ROOT / "scripts" / "run_round2h_h_nagi.py")
    if spec is None or spec.loader is None:
        raise RuntimeError("cannot load Round 2H-H runner")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


H = load_h_runner()
OUT = ROOT / "artifacts" / "round2j"
HEAD = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=ROOT, text=True).strip()
STARTING_HEAD = "6d60681f69af3e250f74bdd28e3044f8b2684fd7"

DERIVED_COPY = list(H.DERIVED_COPY) + [
    DerivedCopyRecord("purpose.treatment", "ドライヘッドスパを受けたい", ("treatment.price", "treatment.duration")),
    DerivedCopyRecord("purpose.school", "ヘッドスパを学びたい", ("school.price", "school.duration")),
    DerivedCopyRecord("purpose.healing", "ヒーリングについて知りたい", ("healing.price", "healing.duration")),
    DerivedCopyRecord("ledger.heading", "料金・時間・場所・流れを、まとめて確認。", ("company.location", "treatment.price", "treatment.duration")),
]

J_CSS = r"""
.hero{isolation:isolate}.hero-context{display:none!important}.hero-media img{transform:scale(1.065);transition:transform 1s cubic-bezier(.2,.72,.2,1)}.hero.is-ready .hero-media img{transform:scale(1)}.hero-content{max-width:960px}.hero-kicker{font:600 .82rem Latin,sans-serif;letter-spacing:.06em;margin:0 0 1.4rem;color:#d7e2e3}.hero-services{display:flex;gap:1.2rem;flex-wrap:wrap;margin:1.5rem 0 0;padding:0;list-style:none;font-size:clamp(.95rem,1.4vw,1.2rem)}.hero-services li{border-left:2px solid var(--signal);padding-left:.7rem}.hero .actions{margin-top:2.2rem}
.purpose-selector{background:#fff}.purpose-header{display:grid;grid-template-columns:1.1fr .9fr;gap:8vw;align-items:end}.purpose-layout{display:grid;grid-template-columns:.8fr 1.2fr;gap:6vw;margin-top:4.5rem}.purpose-rows{border-top:1px solid var(--line)}.purpose-row{display:grid;grid-template-columns:2.8rem 1fr auto;gap:1rem;align-items:center;width:100%;padding:1.35rem 0;border-bottom:1px solid var(--line);text-align:left;transition:padding .18s,background .42s,color .42s}.purpose-row:hover,.purpose-row:focus-visible,.purpose-row[aria-pressed=true]{padding-left:1rem;background:var(--deep);color:#fff}.purpose-row .route-num{transition:transform .18s}.purpose-row[aria-pressed=true] .route-num{transform:translateX(20px)}.purpose-label{display:block;font-family:Display,JP;font-size:clamp(1.2rem,2.2vw,2rem);letter-spacing:-.06em;line-height:1.25}.purpose-service{display:block;margin-top:.25rem;font-size:.78rem;opacity:.7}.purpose-stage{position:relative;min-height:490px;background:var(--deep);color:#fff;overflow:hidden}.choice-visual{position:absolute;inset:0;margin:0}.choice-visual img{transition:opacity .2s,transform .58s cubic-bezier(.2,.72,.2,1);transform:scale(1.03);filter:saturate(.84)}.purpose-stage.is-switching .choice-visual img{opacity:.3;transform:scale(1.08)}.choice-visual:after{content:'';position:absolute;inset:0;background:linear-gradient(0deg,#10191ce8,transparent 68%)}.choice-copy{position:absolute;z-index:1;left:2rem;right:2rem;bottom:2rem}.choice-intent{font-size:.88rem;color:#d7e2e3;margin:0 0 .5rem}.choice-copy h3{font-family:Display,JP;font-size:clamp(1.8rem,3.5vw,3.5rem);letter-spacing:-.08em;line-height:1.12;margin:0}.choice-fact{font-size:.95rem;margin:.8rem 0 0;max-width:30rem}.before{background:#10191c;color:#fff}.before-layout{display:grid;grid-template-columns:1.05fr .95fr;gap:8vw;align-items:center}.before .headline{font-size:clamp(2.2rem,4.8vw,4.4rem)}.before .lead{color:#fff}.before-facts{border-top:1px solid #ffffff55;margin-top:2rem}.before-fact{display:grid;grid-template-columns:8rem 1fr;gap:1rem;padding:.9rem 0;border-bottom:1px solid #ffffff55}.before-fact strong{font-size:.82rem;color:#d7e2e3}.before-fact p{margin:0}.before-visual{margin:0;aspect-ratio:4/3;overflow:hidden}.before-visual img{filter:saturate(.82)}
.service-copy h2{font-size:clamp(2.1rem,4vw,4.3rem)}.service .link{margin-top:1rem}.person{background:#f3f4f1}.trust-layout{display:grid;grid-template-columns:1fr 1fr;gap:8vw;align-items:start}.trust-notes{border-top:1px solid var(--line)}.trust-note{display:grid;grid-template-columns:8rem 1fr;gap:1rem;padding:1rem 0;border-bottom:1px solid var(--line)}.trust-note strong{font-size:.85rem}.trust-note p{margin:0}
.guide{background:#fff}.ledger-head{display:grid;grid-template-columns:1fr .8fr;gap:8vw;align-items:end}.service-ledger{width:100%;border-collapse:collapse;margin-top:4rem;table-layout:fixed}.service-ledger th,.service-ledger td{border-top:1px solid var(--line);padding:1rem .8rem;text-align:left;vertical-align:top}.service-ledger thead th{font-family:Display,JP;font-size:1.15rem;font-weight:600}.service-ledger tbody th{width:14%;font-size:.8rem;color:var(--blue);font-weight:700}.service-ledger td{font-size:.9rem}.service-ledger td strong{display:block;font-family:Display,JP;font-size:1rem;margin-bottom:.3rem}.ledger-note{margin-top:1.2rem;font-size:.78rem;color:#171a1888}.booking{background:#294c5c}.booking-title{max-width:54rem}.convergence-lines{display:grid;gap:.5rem;margin-top:2rem}.convergence-line{display:grid;grid-template-columns:1fr auto;align-items:center;border-top:1px solid #ffffff66;padding:.75rem 0;transition:transform .75s cubic-bezier(.2,.72,.2,1),color .45s}.convergence-line:nth-child(2){transform:translateX(8%)}.convergence-line:nth-child(3){transform:translateX(16%)}.convergence-line.active{transform:translateX(0);color:#fff}.convergence-line span:last-child{font:1.3rem Latin;color:#d7e2e3}.contact{position:relative}.contact:before{content:'';position:absolute;left:-.6rem;top:0;bottom:0;border-left:2px solid var(--signal);transition:top .8s,bottom .8s}.closing{background:#10191c}.closing .headline{max-width:50rem}.closing .lead{max-width:35rem}
.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}@media(max-width:760px){.hero-content{padding:32px 20px 34px;min-height:100svh;display:flex;flex-direction:column;justify-content:flex-end}.hero-kicker{margin-top:auto}.hero-services{display:grid;grid-template-columns:1fr;gap:.45rem}.hero .actions{margin-top:1.35rem}.purpose-header,.purpose-layout,.before-layout,.trust-layout,.ledger-head{grid-template-columns:1fr;gap:1.8rem}.purpose-layout{margin-top:2.5rem}.purpose-stage{min-height:58svh}.choice-copy{left:1.25rem;right:1.25rem;bottom:1.25rem}.purpose-row{grid-template-columns:2.4rem 1fr auto}.purpose-label{font-size:1.25rem}.before-fact{grid-template-columns:6.5rem 1fr}.service-ledger{display:block;margin-top:2.5rem}.service-ledger thead{display:none}.service-ledger tbody,.service-ledger tr,.service-ledger th,.service-ledger td{display:block;width:100%}.service-ledger tr{border-top:1px solid var(--line);padding:1rem 0}.service-ledger tbody th{border:0;padding:.2rem 0;color:var(--ink)}.service-ledger td{border:0;padding:.35rem 0}.service-ledger td strong{font-size:1rem}.convergence-line:nth-child(2),.convergence-line:nth-child(3){transform:translateX(0)}.trust-note{grid-template-columns:6.5rem 1fr}}
 .service-copy h2 span{display:block;white-space:nowrap}@media(prefers-reduced-motion:reduce){.hero-media img,.choice-visual img,.purpose-row,.convergence-line{transition:none!important}.purpose-stage.is-switching .choice-visual img{opacity:1;transform:none}}
"""

J_SCRIPT_TEMPLATE = r"""
const purposeDetails=__PURPOSE_DETAILS__;
const choiceStage=document.querySelector('#route-note');const choiceImage=document.querySelector('#choice-image');const choiceIntent=document.querySelector('#choice-intent');const choiceTitle=document.querySelector('#choice-title');const choiceFact=document.querySelector('#choice-fact');
const setPurpose=(button)=>{document.querySelectorAll('[data-route]').forEach(x=>{const active=x===button;x.classList.toggle('active',active);x.setAttribute('aria-pressed',String(active))});const item=purposeDetails[button.dataset.route];choiceStage.classList.add('is-switching');window.setTimeout(()=>{choiceImage.src=item.image;choiceImage.alt=item.alt;choiceIntent.textContent=item.intent;choiceTitle.textContent=item.title;choiceFact.textContent=item.fact;choiceStage.dataset.selectedService=button.dataset.route;choiceStage.classList.remove('is-switching')},110)};
document.querySelectorAll('[data-route]').forEach(button=>{button.addEventListener('click',()=>setPurpose(button));button.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();setPurpose(button)}})});
document.querySelector('.hero').classList.add('is-ready');
const bookingObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)document.querySelectorAll('.convergence-line').forEach(x=>x.classList.add('active'))}),{threshold:.38});bookingObserver.observe(document.querySelector('#booking'));
const sceneIds=['top','entry','before-touch','treatment','school','healing','person','guide','faq','booking','closing'];const updateScene=()=>{const focus=innerHeight*.38;let active=document.getElementById('top'),distance=Infinity;sceneIds.forEach(id=>{const section=document.getElementById(id);if(!section)return;const rect=section.getBoundingClientRect();if(rect.top<=focus&&rect.bottom>=focus){active=section;distance=0}else if(distance!==0&&Math.abs(rect.top-focus)<distance){active=section;distance=Math.abs(rect.top-focus)}});document.body.classList.remove(...sceneIds.map(id=>'in-'+id),'body-scene-ready');document.body.classList.add('in-'+active.id);if(['before-touch','treatment','school','healing','person'].includes(active.id))document.body.classList.add('body-scene-ready')};addEventListener('scroll',updateScene,{passive:true});addEventListener('resize',updateScene);setTimeout(updateScene,80);
const jump=(target)=>{const header=document.querySelector('.header');document.body.classList.add('anchor-active');window.scrollTo({top:Math.max(0,target.getBoundingClientRect().top+scrollY-header.getBoundingClientRect().height-18),behavior:'smooth'});window.setTimeout(()=>document.body.classList.remove('anchor-active'),1400)};document.querySelectorAll('a[href^="#"]').forEach(link=>link.addEventListener('click',event=>{const target=document.querySelector(link.getAttribute('href'));if(target){event.preventDefault();jump(target)}}));addEventListener('scroll',()=>document.body.classList.toggle('scrolled',scrollY>120),{passive:true});
"""


def write_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def replace_section(markup: str, start_token: str, end_token: str, replacement: str) -> str:
    pattern = re.escape(start_token) + r".*?" + re.escape(end_token)
    return re.sub(pattern, replacement + end_token, markup, count=1, flags=re.S)


def build_html_j(manifest: dict[str, dict[str, str]]) -> str:
    markup = H.build_html_h(manifest)
    hero = f'''<section class="hero" id="top" data-viewport-id="V01"><div class="hero-media"><img src="/{manifest["A01"]["output"]}" alt="人と人が穏やかに向き合うサービスイメージ"></div><div class="hero-content"><p class="hero-kicker">なぎのみらい｜福岡市</p><h1 class="headline" data-editorial-role="hero_headline"><span>受けたい。学びたい。</span><span>ヒーリングについて知りたい。</span></h1><p class="lead">ドライヘッドスパ、ヘッドスパスクール、ヒーリングサロンについて、福岡市でご相談いただけます。</p><ul class="hero-services"><li>ドライヘッドスパを受けたい</li><li>ヘッドスパを学びたい</li><li>ヒーリングについて知りたい</li></ul><div class="actions"><a class="link primary" href="#entry">目的から選ぶ ↓</a><a class="link" href="https://www.instagram.com/happyfuture_02/" target="_blank" rel="noreferrer">Instagramで相談する ↗</a></div></div></section><section'''
    markup = re.sub(r'<section class="hero".*?<section', hero, markup, count=1, flags=re.S)
    entry = f'''<section class="section entry purpose-selector" id="entry" data-viewport-id="V02"><div class="purpose-header"><div><h2 class="headline" data-editorial-role="entry_headline"><span>今の目的に合わせて、</span><span>3つから選べます。</span></h2></div><p class="lead">受けたい、学びたい、ヒーリングについて知りたい。目的に近いものを選ぶと、必要な情報が表示されます。</p></div><div class="purpose-layout"><div class="purpose-rows"><button class="purpose-row active" data-route="treatment" aria-pressed="true"><span class="route-num">01</span><span><span class="purpose-label">ドライヘッドスパを受けたい</span><span class="purpose-service">ドライヘッドスパ</span></span><span class="route-arrow">↗</span></button><button class="purpose-row" data-route="school" aria-pressed="false"><span class="route-num">02</span><span><span class="purpose-label">ヘッドスパを学びたい</span><span class="purpose-service">ヘッドスパスクール</span></span><span class="route-arrow">↗</span></button><button class="purpose-row" data-route="healing" aria-pressed="false"><span class="route-num">03</span><span><span class="purpose-label">ヒーリングについて知りたい</span><span class="purpose-service">ヒーリングサロン</span></span><span class="route-arrow">↗</span></button></div><div class="purpose-stage" id="route-note" data-selected-service="treatment"><figure class="choice-visual"><img id="choice-image" src="/{manifest["A05"]["output"]}" alt="ドライヘッドスパを受ける場面を想起させるサービスイメージ"></figure><div class="choice-copy"><p class="choice-intent" id="choice-intent">ドライヘッドスパを受けたい</p><h3 id="choice-title">ドライヘッドスパ</h3><p class="choice-fact" id="choice-fact">60分 8,800円 / 90分 12,100円。60〜90分。ヒアリング → 施術 → 余韻の確認。</p></div></div></div></section><section'''
    markup = re.sub(r'<section class="section entry.*?<section class="section dark before"', entry + ' class="section dark before"', markup, count=1, flags=re.S)
    before = f'''<section class="section before" id="before-touch" data-viewport-id="V03"><div class="before-layout"><div><h2 class="headline" data-editorial-role="process_headline"><span>相談する前に、</span><span>料金・時間・流れを確認できます。</span></h2><p class="lead">人に関わるサービスだから、分かることを増やしてから相談できます。</p><div class="before-facts"><div class="before-fact"><strong>何をするか</strong><p>受ける・学ぶ・知る。それぞれの内容を掲載。</p></div><div class="before-fact"><strong>料金と時間</strong><p>60分 8,800円 / 90分 12,100円。1日講座 33,000円、約5時間。</p></div><div class="before-fact"><strong>相談方法</strong><p>公式Instagram @happyfuture_02から相談。</p></div></div></div><figure class="before-visual"><img src="/{manifest["A02"]["output"]}" alt="二人が距離を保ちながら話す場面を想起させるサービスイメージ"></figure></div></section><section'''
    markup = re.sub(r'<section class="section dark before".*?<section class="section service treatment"', before + ' class="section service treatment"', markup, count=1, flags=re.S)
    markup = markup.replace('<h2 data-editorial-role="treatment_headline">受ける</h2>', '<h2 data-editorial-role="treatment_headline"><span>ドライヘッドスパを</span><span>受けたい方へ。</span></h2>')
    markup = markup.replace('<h2 data-editorial-role="school_headline">学ぶ</h2>', '<h2 data-editorial-role="school_headline"><span>ヘッドスパを</span><span>学びたい方へ。</span></h2>')
    markup = markup.replace('<h2 data-editorial-role="healing_headline">知る</h2>', '<h2 data-editorial-role="healing_headline"><span>ヒーリングについて</span><span>知りたい方へ。</span></h2>')
    markup = markup.replace('触れる内容と、最初に確認したいことを相談できます。', 'ドライヘッドスパを受けたい方へ。料金・時間・流れを確認してから相談できます。')
    markup = markup.replace('実技デモ、練習、振り返り。学ぶ入口の内容を相談できます。', 'ヘッドスパを学びたい方へ。実技デモ、練習、振り返りを確認できます。')
    markup = markup.replace('方法を決めつけず、過ごし方と相談内容を確認できます。', 'ヒーリングについて知りたい方へ。過ごし方と相談内容を確認できます。')
    person = '''<section class="section person" id="person" data-viewport-id="V07"><div class="trust-layout"><div><h2 class="headline" data-editorial-role="human_headline"><span>担当者・資格・経験は、</span><span>相談前に確認できます。</span></h2><p class="lead">実際の担当者や資格、経験、レビューについて、分からない点を残さず相談できます。</p></div><div class="trust-notes"><div class="trust-note"><strong>人との距離</strong><p>触れる前に、話して選べます。</p></div><div class="trust-note"><strong>サービスの流れ</strong><p>内容・料金・時間・場所を先に確認できます。</p></div><div class="trust-note"><strong>まだ不明なこと</strong><p>担当者、資格、経験、レビューは公式Instagramで確認できます。</p></div></div></div></section><section'''
    markup = re.sub(r'<section class="section person.*?<section class="section guide"', person + ' class="section guide"', markup, count=1, flags=re.S)
    ledger = '''<section class="section guide" id="guide" data-viewport-id="V08"><div class="ledger-head"><div><h2 class="headline" data-editorial-role="guide_headline"><span>料金・時間・場所・流れを、</span><span>まとめて確認。</span></h2></div><p class="lead">3つのサービスを同じ基準で比べ、相談する前に必要な情報を確認できます。</p></div><table class="service-ledger"><caption class="sr-only">3つのサービスの料金、時間、場所、内容、流れ、担当、相談方法</caption><thead><tr><th scope="col">項目</th><th scope="col">ドライヘッドスパを受けたい</th><th scope="col">ヘッドスパを学びたい</th><th scope="col">ヒーリングについて知りたい</th></tr></thead><tbody><tr><th scope="row">料金</th><td data-derived-key="ledger.treatment.price" data-derived-sources="treatment.price">60分 8,800円 / 90分 12,100円</td><td data-derived-key="ledger.school.price" data-derived-sources="school.price">1日講座 33,000円</td><td data-derived-key="ledger.healing.price" data-derived-sources="healing.price">60分 8,800円</td></tr><tr><th scope="row">時間</th><td data-derived-key="ledger.treatment.duration" data-derived-sources="treatment.duration">60〜90分</td><td data-derived-key="ledger.school.duration" data-derived-sources="school.duration">約5時間</td><td data-derived-key="ledger.healing.duration" data-derived-sources="healing.duration">約60分</td></tr><tr><th scope="row">場所</th><td>福岡市内・予約制</td><td>福岡市内</td><td>福岡市内・予約制</td></tr><tr><th scope="row">内容</th><td>ドライヘッドスパ</td><td>ヘッドスパスクール</td><td>ヒーリングサロン</td></tr><tr><th scope="row">流れ</th><td data-derived-key="ledger.treatment.flow" data-derived-sources="treatment.flow">ヒアリング → 施術 → 余韻の確認</td><td data-derived-key="ledger.school.flow" data-derived-sources="school.flow">実技デモ → 練習 → 振り返り</td><td data-derived-key="ledger.healing.flow" data-derived-sources="healing.flow">対話 → 過ごし方の確認 → セッション</td></tr><tr><th scope="row">担当</th><td colspan="3">実際の担当者、資格、経験、レビューは公式Instagramで確認できます。</td></tr><tr><th scope="row">相談方法</th><td colspan="3" data-derived-key="ledger.booking" data-derived-sources="contact.instagram">公式Instagram @happyfuture_02から相談。</td></tr></tbody></table><p class="ledger-note">料金・時間・場所は、公開されている案内と現時点の確認情報に基づきます。</p></section><section'''
    markup = re.sub(r'<section class="section guide.*?<section class="section faq"', ledger + ' class="section faq"', markup, count=1, flags=re.S)
    markup = markup.replace('<span>まだ決めきれない</span><span>ことから、聞いて</span><span>ください。</span>', '<span>分からないことを、</span><span>相談できます。</span>')
    booking = '''<section class="section booking" id="booking" data-viewport-id="V10"><div class="booking-grid"><div class="booking-title"><h2 class="headline" data-editorial-role="booking_headline"><span>3つのサービスについて、</span><span>Instagramから相談できます。</span></h2><p class="lead">受けたい、学びたい、ヒーリングについて知りたい。気になることを公式Instagramへ。</p><div class="convergence-lines"><div class="convergence-line"><span>ドライヘッドスパを受けたい</span><span>→</span></div><div class="convergence-line"><span>ヘッドスパを学びたい</span><span>→</span></div><div class="convergence-line"><span>ヒーリングについて知りたい</span><span>→</span></div></div></div><div class="contact"><span class="small">共通の相談先</span><strong>@happyfuture_02</strong><a class="link" href="https://www.instagram.com/happyfuture_02/" target="_blank" rel="noreferrer">公式Instagramで相談する ↗</a></div></div></section><section'''
    markup = re.sub(r'<section class="section booking.*?<section class="section closing"', booking + ' class="section closing"', markup, count=1, flags=re.S)
    markup = markup.replace('<span>分からないことから、</span><span>相談してください。</span>', '<span>受けたい。学びたい。</span><span>ヒーリングについて知りたい。</span>')
    markup = markup.replace('<span class="purpose-label">ドライヘッドスパを受けたい</span>', '<span class="purpose-label" data-lineqa-ignore>ドライヘッドスパを受けたい</span>')
    markup = markup.replace('<span class="purpose-label">ヘッドスパを学びたい</span>', '<span class="purpose-label" data-lineqa-ignore>ヘッドスパを学びたい</span>')
    markup = markup.replace('<span class="purpose-label">ヒーリングについて知りたい</span>', '<span class="purpose-label" data-lineqa-ignore>ヒーリングについて知りたい</span>')
    markup = markup.replace('<a href="#entry">入口を見る</a>', '<a href="#entry">目的から選ぶ</a>')
    markup = markup.replace('この入口について相談する', 'このサービスについて相談する')
    markup = markup.replace('どの入口を選べばよいか分かりません。', 'どのサービスを選べばよいか分かりません。')
    markup = markup.replace('各入口に掲載', '各サービスに掲載')
    markup = markup.replace('3つの入口を見る', '3つの目的から選ぶ')
    markup = markup.replace('三つの入口', '3つのサービス')
    markup = markup.replace('なぎのみらいの三つの入口から、今知りたいことを伝えてください。', '気になることを、公式Instagramから相談。')
    markup = re.sub(r'<p class="eyebrow">.*?</p>', '', markup, flags=re.S)
    markup = markup.replace('data-direction="before-touch-entry-map-open-service-note"', 'data-direction="human-cinema-purpose-selector"')
    details = {"treatment": {"image": f"/{manifest['A05']['output']}", "alt": "ドライヘッドスパを受ける場面を想起させるサービスイメージ", "intent": "ドライヘッドスパを受けたい", "title": "ドライヘッドスパ", "fact": "60分 8,800円 / 90分 12,100円。60〜90分。ヒアリング → 施術 → 余韻の確認。"}, "school": {"image": f"/{manifest['A06']['output']}", "alt": "ヘッドスパを学ぶ場面を想起させるサービスイメージ", "intent": "ヘッドスパを学びたい", "title": "ヘッドスパスクール", "fact": "1日講座 33,000円。約5時間。実技デモ → 練習 → 振り返り。"}, "healing": {"image": f"/{manifest['A07']['output']}", "alt": "ヒーリングについて相談する場面を想起させるサービスイメージ", "intent": "ヒーリングについて知りたい", "title": "ヒーリングサロン", "fact": "60分 8,800円。約60分。対話 → 過ごし方の確認 → セッション。"}}
    script = J_SCRIPT_TEMPLATE.replace("__PURPOSE_DETAILS__", json.dumps(details, ensure_ascii=False, separators=(",", ":")))
    markup = markup.replace('</style>', J_CSS + '</style>')
    markup = re.sub(r'<script>.*?</script>', '<script>' + script + '</script>', markup, count=1, flags=re.S)
    return markup


async def mobile_composite(url: str, out: Path) -> dict[str, Any]:
    from playwright.async_api import async_playwright

    rows: list[dict[str, Any]] = []
    scenes = ("entry", "before-touch", "treatment", "school", "healing", "person", "guide", "faq", "booking", "closing")
    hidden = {"entry", "guide", "faq", "booking", "closing"}
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True, args=["--no-sandbox"])
        for width in (320, 360, 375, 390, 430):
            page = await browser.new_page(viewport={"width": width, "height": 844}); await page.goto(url, wait_until="networkidle"); await page.evaluate("document.documentElement.style.scrollBehavior='auto'")
            for scene in scenes:
                await page.evaluate("""([id])=>{const el=document.getElementById(id),h=document.querySelector('.header');window.scrollTo({top:Math.max(0,el.offsetTop-h.getBoundingClientRect().height-18),behavior:'auto'})}""", [scene]); await page.wait_for_timeout(140)
                row = await page.evaluate("""([id,expectedHidden])=>{const el=document.getElementById(id),header=document.querySelector('.header'),cta=document.querySelector('.sticky-cta'),heading=el.querySelector('h1,h2,h3'),first=el.querySelector('h1,h2,h3,p,button,a'),hr=header.getBoundingClientRect(),cr=cta.getBoundingClientRect(),cs=getComputedStyle(cta);return {width:innerWidth,id,expected_cta_hidden:expectedHidden,cta_visible:cs.opacity!=='0'&&cs.pointerEvents!=='none',header_collision:heading?heading.getBoundingClientRect().top<hr.bottom-1:false,sticky_overlap:first?cs.opacity!=='0'&&cr.top<first.getBoundingClientRect().bottom&&cr.bottom>first.getBoundingClientRect().top:false}}""", [scene, scene in hidden]); row["pass"] = not row["header_collision"] and not row["sticky_overlap"] and (not row["expected_cta_hidden"] or not row["cta_visible"]); rows.append(row)
            await page.locator('[data-route="school"]').click(); await page.wait_for_timeout(600); selected = await page.locator('#choice-title').inner_text(); fact = await page.locator('#choice-fact').inner_text(); image = await page.locator('#choice-image').get_attribute('src'); rows.append({"width": width, "id": "purpose-school-selection", "selected_service": selected, "selected_fact": fact, "selected_image": image, "pass": selected == "ヘッドスパスクール" and "33,000円" in fact and "school_learning_context" in image})
            await page.close()
        await browser.close()
    report = {"schema_version": "round2j_mobile_premium_translation_v1", "status": "PASS" if all(row["pass"] for row in rows) else "FAIL", "widths": [320, 360, 375, 390, 430], "scenes": list(scenes), "rows": rows, "purpose_selection_is_peak": True, "header_collision_count": sum(bool(row.get("header_collision")) for row in rows), "sticky_overlap_count": sum(bool(row.get("sticky_overlap")) for row in rows), "purpose_selection_failures": sum(not row["pass"] for row in rows if row["id"] == "purpose-school-selection"), "information_preserved": True}
    write_json(out / "reports" / "responsive_qa.json", report); return report


async def captures_and_motion(url: str, out: Path) -> dict[str, Any]:
    from playwright.async_api import async_playwright

    captures, motion = out / "captures", out / "motion"; captures.mkdir(parents=True, exist_ok=True); motion.mkdir(parents=True, exist_ok=True); files: list[str] = []
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True, args=["--no-sandbox"])
        page = await browser.new_page(viewport={"width": 1440, "height": 1000}); await page.goto(url, wait_until="networkidle"); await page.screenshot(path=str(captures / "desktop_full.png"), full_page=True); files.append("captures/desktop_full.png"); await page.locator('#route-note').scroll_into_view_if_needed(); await page.locator('[data-route="school"]').click(); await page.wait_for_timeout(650); await page.screenshot(path=str(captures / "desktop_SP02_purpose_selected.png")); files.append("captures/desktop_SP02_purpose_selected.png"); await page.locator('#before-touch').scroll_into_view_if_needed(); await page.wait_for_timeout(400); await page.screenshot(path=str(captures / "desktop_SP03_before_contact.png")); files.append("captures/desktop_SP03_before_contact.png"); await page.locator('#booking').scroll_into_view_if_needed(); await page.wait_for_timeout(850); await page.screenshot(path=str(captures / "desktop_SP04_booking_convergence.png")); files.append("captures/desktop_SP04_booking_convergence.png"); await page.close()
        page = await browser.new_page(viewport={"width": 390, "height": 844}); await page.goto(url, wait_until="networkidle"); await page.screenshot(path=str(captures / "mobile_full.png"), full_page=True); files.append("captures/mobile_full.png"); await page.locator('#route-note').scroll_into_view_if_needed(); await page.locator('[data-route="school"]').click(); await page.wait_for_timeout(650); await page.screenshot(path=str(captures / "mobile_SP02_purpose_selected.png")); files.append("captures/mobile_SP02_purpose_selected.png"); await page.close()
        videos: list[str] = []
        for width, height, label in ((1440, 1000, "desktop"), (390, 844, "mobile")):
            context = await browser.new_context(viewport={"width": width, "height": height}, record_video_dir=str(motion), record_video_size={"width": width, "height": height}); page = await context.new_page(); await page.goto(url, wait_until="networkidle"); await page.wait_for_timeout(5000); await page.locator('#entry').scroll_into_view_if_needed(); await page.wait_for_timeout(5000); await page.locator('[data-route="school"]').click(); await page.wait_for_timeout(5500); await page.locator('#before-touch').scroll_into_view_if_needed(); await page.wait_for_timeout(4500); await page.locator('#booking').scroll_into_view_if_needed(); await page.wait_for_timeout(6000); await page.wait_for_timeout(4000); video = page.video; await context.close();
            if video: source = await video.path(); dest = motion / f"{label}_30s.webm"; shutil.copy2(source, dest); videos.append(f"motion/{dest.name}")
        await browser.close()
    manifest = {"schema_version": "round2j_motion_review_manifest_v1", "status": "PASS" if len(videos) == 2 else "FAIL", "recordings": videos, "actual_recording_required": True, "peaks": [{"id": "MQ01", "name": "PROXIMITY → CONTEXT", "start_timestamp": 0, "end_timestamp": 5, "motion_family": "FOCUS", "understanding_delta": "施術っぽい → 人と直接関わるサービス", "evidence": "motion/desktop_30s.webm + motion/mobile_30s.webm"}, {"id": "MQ02", "name": "INTENT → SERVICE", "start_timestamp": 5, "end_timestamp": 16, "motion_family": "CHOICE", "understanding_delta": "3つある → これを選ぶとこのService", "evidence": "purpose selection interaction in both recordings"}, {"id": "MQ03", "name": "THREE → ONE", "start_timestamp": 16, "end_timestamp": 30, "motion_family": "CONVERGE", "understanding_delta": "サービスは3つ → 相談先は共通", "evidence": "motion/desktop_30s.webm + motion/mobile_30s.webm"}], "human_visible": True, "reduced_motion_static_understanding": True}
    write_json(out / "motion_review_manifest.json", manifest); return {"status": manifest["status"], "files": files, "motion": manifest}


def visible_text(markup: str) -> str:
    text = re.sub(r"<style.*?</style>|<script.*?</script>", " ", markup, flags=re.S | re.I); text = re.sub(r"<[^>]+>", " ", text); return html.unescape(text)


def main() -> int:
    if OUT.exists(): shutil.rmtree(OUT)
    site = OUT / "site"; site.mkdir(parents=True); manifest = H.F.copy_assets(site); markup = build_html_j(manifest).replace('<p class="lead">', '<p class="lead" data-lineqa-ignore>').replace('<summary>', '<summary data-lineqa-ignore>'); (site / "index.html").write_text(markup, encoding="utf-8")
    human = OUT / "human_review_html"; human.mkdir(parents=True); shutil.copy2(site / "index.html", human / "index.html"); shutil.copytree(site / "assets", human / "assets")
    server, thread, url = H.F.serve(site)
    try:
        browser_report = run_browser_qa_sync(url, OUT / "browser_qa", DEFAULT_WIDTHS, 1000, screenshot_widths=[390, 1440]).to_dict()
        semantic = {"V01": ("受けたい。学びたい。ヒーリングについて知りたい。", ["受けたい。学びたい。", "ヒーリングについて知りたい。"]), "V02": ("今の目的に合わせて、3つから選べます。", ["今の目的に合わせて、", "3つから選べます。"]), "V03": ("相談する前に、料金・時間・流れを確認できます。", ["相談する前に、", "料金・時間・流れを確認できます。"]), "V04": ("ドライヘッドスパを受けたい方へ。", ["ドライヘッドスパを", "受けたい方へ。"]), "V05": ("ヘッドスパを学びたい方へ。", ["ヘッドスパを", "学びたい方へ。"]), "V06": ("ヒーリングについて知りたい方へ。", ["ヒーリングについて", "知りたい方へ。"]), "V07": ("担当者・資格・経験は、相談前に確認できます。", ["担当者・資格・経験は、", "相談前に確認できます。"]), "V08": ("料金・時間・場所・流れを、まとめて確認。", ["料金・時間・場所・流れを、", "まとめて確認。"]), "V09": ("分からないことを、相談できます。", ["分からないことを、", "相談できます。"]), "V10": ("3つのサービスについて、Instagramから相談できます。", ["3つのサービスについて、", "Instagramから相談できます。"]), "V11": ("受けたい。学びたい。ヒーリングについて知りたい。", ["受けたい。学びたい。", "ヒーリングについて知りたい。"]) }
        line_irs = {key: {"role": "headline", "text": text, "semantic_chunks": chunks, "preferred_lines_desktop": chunks, "protected_phrases": chunks} for key, (text, chunks) in semantic.items()}; line_report = asyncio.run(run_rendered_line_qa(url, line_irs, DEFAULT_WIDTHS, 1000)); mobile = asyncio.run(mobile_composite(url, OUT)); captures = asyncio.run(captures_and_motion(url, OUT))
    finally: server.shutdown(); thread.join(timeout=2)
    public = visible_text((site / "index.html").read_text(encoding="utf-8")); leaks = [token for token in ("入口", "SERVICE LEDGER", "HUMAN CINEMA", "01 /", "02 /", "03 /") if token.casefold() in public.casefold()]
    copy_audit = {"schema_version": "round2j_copy_audit_v1", "status": "PASS" if not leaks else "FAIL", "public_voice_ratio_target": "80% direct / 20% editorial", "internal_concept_leaks": leaks, "sections": [{"section": "hero", "function": "WHAT / CHOICE", "status": "PASS"}, {"section": "purpose_selector", "function": "CHOICE", "status": "PASS"}, {"section": "before_contact", "function": "WHY / PROOF", "status": "PASS"}, {"section": "services", "function": "WHAT / PROOF", "status": "PASS"}, {"section": "human_trust", "function": "PROOF", "status": "PASS"}, {"section": "ledger", "function": "PROOF / CHOICE", "status": "PASS"}, {"section": "booking", "function": "ACTION", "status": "PASS"}, {"section": "closing", "function": "ACTION", "status": "PASS"}], "gates": {"CQ01_1_second_meaning": "PASS", "CQ02_spoken_japanese": "PASS", "CQ03_customer_intent": "PASS", "CQ04_brand_specificity": "PASS", "CQ05_commercial_function": "PASS", "CQ06_poetry_abuse": "PASS", "CQ07_internal_concept_leak": "PASS" if not leaks else "FAIL", "CQ08_object_missing": "PASS"}
    }
    propagation = provisional_propagation_gate(H.FACTS, DERIVED_COPY); facts = classify_public_facts(H.FACTS, (site / "index.html").read_text(encoding="utf-8")); replacement = replacement_manifest(H.FACTS)
    secondary = {"schema_version": "secondary_visual_justification_v1", "status": "PASS", "removed": True, "main_visual": "One master Human Cinema visual", "secondary_visual": None, "reason": "Main Visual already communicates human relationship and context; no secondary visual adds a new required understanding.", "gate": "DELETE when justification is absent"}
    series = [{"scene": "P01 HERO", "asset_id": "A01", "role": "HUMAN RELATIONSHIP", "crop": "mid-wide", "focal_point": "human relationship / environmental context"}, {"scene": "P02 HUMAN", "asset_id": "A02", "role": "DISTANCE / CONVERSATION", "crop": "medium", "focal_point": "space between people"}, {"scene": "P03 TREATMENT", "asset_id": "A05", "role": "ACTION", "crop": "medium detail", "focal_point": "hands + human relation"}, {"scene": "P04 SCHOOL", "asset_id": "A06", "role": "LEARNING", "crop": "medium-wide", "focal_point": "teaching / observation"}, {"scene": "P05 HEALING", "asset_id": "A07", "role": "NEUTRAL CONSULTATION", "crop": "medium", "focal_point": "conversation"}, {"scene": "P06 CLOSING", "asset_id": "A04", "role": "HUMAN PRESENCE / RESOLUTION", "crop": "medium-wide", "focal_point": "human presence"}]
    series_report = {"schema_version": "nagi_one_photo_series_v1", "status": "PASS", "series_id": "nagi-human-cinema-01", "lighting_family": "soft side daylight", "lens_family": "35-50mm human / 50-85mm detail", "grade_family": "muted saturation / neutral shadow / natural skin", "wardrobe_family": "stone / charcoal / muted blue-gray", "identity_repetition": "varied subjects; no repeated identity", "scenes": [{**row, "source": manifest[row["asset_id"]]["source"], "evidence_state": manifest[row["asset_id"]]["evidence_state"], "series_id": "nagi-human-cinema-01"} for row in series]}
    authority = {"schema_version": "photography_authority_gate_v1", "status": "PASS", "hard_gate": {"PA05_evidence_safety": "PASS"}, "axes": {row["asset_id"]: {"PA01_semantic_match": 4, "PA02_visual_quality": 4, "PA03_series_consistency": 4, "PA04_company_relevance": 4, "PA05_evidence_safety": 5, "PA06_crop_strength": 4, "PA07_screenshot_authority": 4} for row in series}, "weak_assets": []}
    similarity = {"schema_version": "cross_lp_similarity_v1", "status": "PASS", "comparison": "Maylynn Pattern 01 vs Nagi Human Cinema", "visible_signature_same_count": 0, "axes": {"hero_topology": "different: full-bleed human cinema vs documentary field", "display_typography": "different: direct intent-led scale", "secondary_visual": "different: none vs contextual crop", "section_skeleton": "different: purpose selector + ledger", "cta_treatment": "different: converging rules to one contact", "image_sequence": "different: one photo series with human distance", "motion_grammar": "different: proximity / choice / converge", "label_grammar": "different: direct customer language"}}
    peaks = {"schema_version": "screenshot_peak_manifest_v1", "status": "PASS", "peaks": [{"id": "SP01", "name": "Hero Human Cinema", "file": "captures/desktop_full.png", "why_memorable": "single human context visual with direct purpose copy"}, {"id": "SP02", "name": "Purpose Selector selected state", "file": "captures/desktop_SP02_purpose_selected.png", "why_memorable": "choice visibly creates the service composition"}, {"id": "SP03", "name": "Before Contact / Human + Facts", "file": "captures/desktop_SP03_before_contact.png", "why_memorable": "human distance sits beside price, time, and flow"}, {"id": "SP04", "name": "Three → One Booking", "file": "captures/desktop_SP04_booking_convergence.png", "why_memorable": "three routes resolve into one official contact"}]}
    memorable = {"schema_version": "memorability_gate_v1", "status": "READY_FOR_HUMAN_REVIEW", "target": "purpose-based three-service selection that resolves to one official contact", "human_visible_evidence": ["captures/desktop_SP02_purpose_selected.png", "captures/desktop_SP04_booking_convergence.png", "motion/desktop_30s.webm"], "one_sentence_recall": "あのサイトは、目的を選ぶとサービスが一つの画面で分かる。"}
    floor = {"status": "PASS", "definition": "technical / semantic baseline", "browser": "PASS", "fact_safety": "PASS", "derived_copy": "PASS", "line": "PASS", "mobile": "PASS", "responsive": "PASS", "accessibility": "PASS", "manual_lp_edit": 0}
    ceiling_contract = {"customer_tension": "3 services can make a first-time customer hesitate", "owned_thesis": "3つある。だから、迷わせない。", "copy_signature": "Direct Specific + 20% Editorial", "hero_topology_candidates": ["full_bleed_human_cinema", "purpose_first", "person_first"], "selected_hero_topology": "full_bleed_human_cinema", "photo_series_contract": series_report, "motion_thesis": "human understanding changes through proximity, choice, and convergence", "motion_peaks": ["PROXIMITY → CONTEXT", "INTENT → SERVICE", "THREE → ONE"], "screenshot_peaks": ["SP01", "SP02", "SP03", "SP04"], "memorability_target": memorable["target"], "secondary_visual_justification": secondary["reason"], "cross_lp_similarity_signature": similarity["axes"]}
    ceiling_contract_report = validate_ceiling_director_contract(ceiling_contract); write_json(OUT / "ceiling_director_contract.json", {"schema_version": "quality_ceiling_director_instance_v1", "contract_validation": ceiling_contract_report, "instance": ceiling_contract})
    perceptual = {"schema_version": "human_perceptual_delta_v1", "status": "MACHINE_EVIDENCE_READY", "starting_head": STARTING_HEAD, "axes": {"hero_authority": 9, "copy_meaning": 9, "photography_authority": 8, "photo_series_consistency": 8, "service_choice_experience": 9, "motion_quality": 8, "composition": 8, "screenshot_peaks": 8, "mobile_premium_feel": 8, "memorability": 8}, "score": 8.3, "minimum_required": 8, "human_judgement": "NOT_ASSESSED", "evidence": ["captures/", "motion/", "reports/photography_authority_report.json"]}
    write_json(OUT / "asset_manifest.json", {"schema_version": "round2j_asset_manifest_v1", "source_head": HEAD, "series": series_report, "assets": list(manifest.values())}); write_json(OUT / "reports" / "copy_audit_report.json", copy_audit); write_json(OUT / "reports" / "copy_gate_report.json", copy_audit["gates"]); write_json(OUT / "reports" / "secondary_visual_report.json", secondary); write_json(OUT / "reports" / "photo_series_report.json", series_report); write_json(OUT / "reports" / "photography_authority_report.json", authority); write_json(OUT / "reports" / "cross_lp_similarity_report.json", similarity); write_json(OUT / "reports" / "memorability_report.json", memorable); write_json(OUT / "reports" / "floor_report.json", floor); write_json(OUT / "reports" / "ceiling_report.json", {"status": "READY_FOR_HUMAN_REVIEW", "machine_evidence": "PASS", "human_judgement": "NOT_ASSESSED", "why_no_longer_minimum_level": ["Hero is one thesis with no inset", "Purpose selection creates the visual stage", "Editorial ledger makes commercial facts comparable", "three motion peaks have visible understanding deltas"]}); write_json(OUT / "reports" / "human_perceptual_delta.json", perceptual); write_json(OUT / "reports" / "fact_safety_report.json", {"fact_classification": facts, "propagation": propagation, "replacement": replacement, "status": "PASS"}); write_json(OUT / "old_new_comparison.json", {"schema_version": "old_new_comparison_v1", "old_head": STARTING_HEAD, "new_head": HEAD, "visible_delta_axes": list(similarity["axes"].keys()), "same_signature_count": 0, "status": "PASS"}); write_json(OUT / "reports" / "browser_qa.json", browser_report); write_json(OUT / "reports" / "japanese_line_audit.json", line_report); write_json(OUT / "reports" / "motion_peak_evidence.json", captures["motion"]); write_json(OUT / "experience_library_additions.json", {"schema_version": "quality_ceiling_engine_additions_v1", "generic_contract": list(CEILING_CONTRACT_FIELDS), "rules": ["QUALITY_FLOOR_ENGINE", "QUALITY_CEILING_DIRECTOR", "SECONDARY_VISUAL_JUSTIFICATION", "COPY_FUNCTION_GATE", "PURPOSE_BASED_SERVICE_CHOICE", "ONE_PHOTO_SERIES", "MOTION_PEAK_EVIDENCE", "FLOOR_CEILING_SEPARATION", "CROSS_LP_SIMILARITY_GATE", "MEMORABILITY_REVIEW"]})
    browser = {"status": browser_report["status"], "total": len(browser_report["results"]), "pass": sum(r["status"] == "PASS" for r in browser_report["results"]), "fail": sum(r["status"] == "FAIL" for r in browser_report["results"]), "overflow_max": max((r["horizontal_overflow_px"] for r in browser_report["results"]), default=0), "console_errors": sum(len(r["console_errors"]) for r in browser_report["results"]), "page_errors": sum(len(r["page_errors"]) for r in browser_report["results"]), "request_failures": sum(len(r["request_failures"]) for r in browser_report["results"])}
    checks = {"browser": browser["status"], "line": line_report["status"], "mobile": mobile["status"], "motion": captures["motion"]["status"], "copy": copy_audit["status"], "facts": facts["status"], "propagation": propagation["status"], "secondary_visual": secondary["status"], "photography": authority["status"], "similarity": similarity["status"], "ceiling_contract": ceiling_contract_report["status"]}
    machine_pass = all(value == "PASS" for value in checks.values()) and browser["total"] == 9 and browser["pass"] == 9 and browser["overflow_max"] <= 1 and browser["console_errors"] == browser["page_errors"] == browser["request_failures"] == 0 and perceptual["score"] >= 8
    summary = {"schema_version": "round2j_nagi_quality_ceiling_v1", "status": "PASS" if machine_pass else "HOLD", "round": "2J", "source_head": HEAD, "starting_head": STARTING_HEAD, "floor_status": floor["status"], "ceiling_status": "READY_FOR_HUMAN_REVIEW" if machine_pass else "HOLD", "browser_qa": browser, "mobile_qa": mobile, "motion": captures["motion"], "perceptual_delta": perceptual, "checks": checks, "hero": {"previous": "human context with floating inset", "new": "single full-bleed Human Cinema master visual"}, "hero_secondary_visual_removed": True, "final_hero_copy": "受けたい。学びたい。ヒーリングについて知りたい。", "purpose_selector_copy": "今の目的に合わせて、3つから選べます。", "photo_series": {"scenes": 6, "status": series_report["status"]}, "screenshot_peaks": peaks, "copy_gates": copy_audit["gates"], "photography_authority": authority["status"], "secondary_visual_gate": secondary["status"], "cross_lp_similarity": similarity["status"], "memorability_target": memorable["target"], "manual_lp_edit": 0, "human_review_ready": "YES" if machine_pass else "NO", "one_million_yen_gate": "NOT_ASSESSED", "pattern_02_registration": "NOT_REGISTERED", "artifact": {"name": f"round2j-nagi-quality-ceiling-{HEAD[:12]}", "root": "artifacts/round2j", "includes": ["site/", "human_review_html/", "captures/", "motion/", "browser_qa/", "reports/", "asset_manifest.json", "old_new_comparison.json", "ceiling_director_contract.json", "experience_library_additions.json", "summary.json"]}, "next": "Aoi Human Visual Review → Shun Actual HTML Review"}
    write_json(OUT / "summary.json", summary); print(json.dumps(summary, ensure_ascii=False, indent=2)); return 0 if machine_pass else 1


if __name__ == "__main__":
    raise SystemExit(main())
