"""Round 2Q: Nagi First Creative x Growth Prototype.

This runner keeps the Round 2J floor and replaces its presentation with a
growth-aware, human-readable prototype.  It is intentionally a sales sample:
the acquisition channel remains UNKNOWN and Instagram is the only verified
public contact.
"""
from __future__ import annotations

import asyncio
import html
import importlib.util
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
from lp_engine.browser_qa import DEFAULT_WIDTHS, run_browser_qa_sync, run_rendered_line_qa
from lp_engine.ceiling_director import CEILING_CONTRACT_FIELDS, validate_ceiling_director_contract
from lp_engine.sales_sample_policy import classify_public_facts, provisional_propagation_gate, replacement_manifest


def load_j_runner():
    spec = importlib.util.spec_from_file_location("round2j_nagi_quality_ceiling", ROOT / "scripts" / "run_round2j_nagi_quality_ceiling.py")
    if spec is None or spec.loader is None:
        raise RuntimeError("cannot load Round 2J runner")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


J = load_j_runner()
H = J.H
OUT = ROOT / "artifacts" / "round2q"
HEAD = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=ROOT, text=True).strip()
STARTING_HEAD = "e536d3239f0011ca09674565ec160073afadb603"
INSTAGRAM = "https://www.instagram.com/happyfuture_02/"

Q_CSS = r"""
/* Round 2Q: direct commercial clarity, not a cosmetic J patch. */
.header{mix-blend-mode:normal;color:#fff;background:linear-gradient(180deg,rgba(16,25,28,.82),rgba(16,25,28,0));transition:background .35s,color .35s,backdrop-filter .35s}.header.scrolled,.scrolled .header{background:rgba(243,244,241,.96);color:var(--ink);backdrop-filter:blur(8px)}.hero{min-height:100svh}.hero-media:after{background:linear-gradient(90deg,rgba(16,25,28,.88),rgba(16,25,28,.25) 68%,rgba(16,25,28,.18)),linear-gradient(0deg,rgba(16,25,28,.82),transparent 65%)}.hero-media img{object-position:78% 50%;transform:scale(1.035);transition:object-position 1.2s cubic-bezier(.2,.72,.2,1),transform 1.2s cubic-bezier(.2,.72,.2,1),filter 1.2s}.hero.hero-mid .hero-media img{object-position:62% 48%;transform:scale(1.015);filter:saturate(.9)}.hero.hero-end .hero-media img{object-position:50% 45%;transform:scale(1);filter:saturate(.96)}.hero-content{max-width:900px}.hero-kicker{font:700 .82rem Latin,sans-serif;letter-spacing:.08em;margin:0 0 1.2rem;color:#fff}.hero h1{max-width:14em}.hero h1 span{display:block;white-space:nowrap}.hero .lead{max-width:38rem;color:#fff}.hero-services{display:flex;gap:1rem;flex-wrap:wrap;margin:1.4rem 0 0;padding:0;list-style:none;font-size:.92rem}.hero-services li{border-left:2px solid var(--signal);padding-left:.65rem}.hero-motion-note{position:absolute;right:clamp(20px,7vw,110px);bottom:2.2rem;z-index:2;font-size:.72rem;color:#ffffffc9;letter-spacing:.08em}
.purpose-selector{background:#fff}.purpose-header{display:grid;grid-template-columns:1fr 1fr;gap:8vw;align-items:end}.purpose-header .lead{max-width:30rem}.purpose-layout{display:grid;grid-template-columns:.85fr 1.15fr;gap:5vw;margin-top:4.2rem}.purpose-rows{border-top:1px solid var(--line)}.purpose-row{display:grid;grid-template-columns:2.5rem 1fr auto;gap:1rem;align-items:center;width:100%;padding:1.25rem 0;border-bottom:1px solid var(--line);text-align:left;transition:padding .2s,background .32s,color .32s}.purpose-row:hover,.purpose-row:focus-visible,.purpose-row[aria-pressed=true]{padding-left:1rem;background:var(--deep);color:#fff}.purpose-label{display:block;font-family:Display,JP;font-size:clamp(1.15rem,2vw,1.7rem);letter-spacing:-.05em;line-height:1.25;white-space:nowrap}.purpose-intent{display:block;margin-top:.2rem;font-size:.82rem;opacity:.72}.purpose-service{display:none}.purpose-row[aria-pressed=true] .purpose-intent{opacity:.9}.purpose-stage{position:relative;min-height:510px;background:var(--deep);color:#fff;overflow:hidden}.choice-visual{position:absolute;inset:0;margin:0}.choice-visual img{transition:opacity .18s,transform .42s cubic-bezier(.2,.72,.2,1);transform:scale(1.02);filter:saturate(.86)}.purpose-stage.is-preview .choice-visual img{transform:scale(1.06);opacity:.88}.choice-visual:after{content:'';position:absolute;inset:0;background:linear-gradient(0deg,#10191cee,transparent 70%)}.choice-copy{position:absolute;z-index:1;left:2rem;right:2rem;bottom:2rem}.choice-intent{font-size:.85rem;color:#d7e2e3;margin:0 0 .5rem}.choice-copy h3{font-family:Display,JP;font-size:clamp(1.8rem,3.5vw,3.4rem);letter-spacing:-.08em;line-height:1.12;margin:0;white-space:nowrap}.choice-fact{font-size:.94rem;margin:.8rem 0 0;max-width:32rem}.selector-support{margin:1.6rem 0 0;font-size:.9rem;max-width:28rem}.selector-support strong{display:block;font-family:Display,JP;font-size:1.05rem;margin-bottom:.3rem}.selector-support span{display:block;color:#171a1888}
.before{background:#10191c;color:#fff}.before-layout{display:grid;grid-template-columns:5fr 7fr;gap:7vw;align-items:center}.before .headline{font-size:clamp(2.2rem,4.5vw,4.1rem)}.before .lead{color:#fff}.before-facts{border-top:1px solid #ffffff55;margin-top:2rem}.before-fact{padding:.85rem 0;border-bottom:1px solid #ffffff55}.before-fact strong{font-size:.82rem;color:#d7e2e3}.before-fact p{margin:.2rem 0}.before-visual{margin:0;aspect-ratio:4/5;overflow:hidden}.before-visual img{filter:saturate(.84)}
.service-copy h2{font-size:clamp(2.1rem,4vw,4.1rem)}.service-copy h2 span{display:block;white-space:nowrap}.service-copy .lead{max-width:31rem}.service-purpose{font:700 .75rem Latin;letter-spacing:.1em;color:var(--blue);margin:0}.service-facts{display:grid;grid-template-columns:repeat(2,1fr);gap:1rem;margin:1.6rem 0}.service-fact{border-top:1px solid var(--line);padding-top:.55rem}.service-fact strong{display:block;font-size:.78rem}.service-fact p{margin:.2rem 0;font-size:.88rem}.service.school{background:#e9edef}.service.healing{background:#eef0ed}.service-ledger [data-ledger-service].is-emphasized{background:#e6eee8;box-shadow:inset 3px 0 var(--signal);transition:background .4s}.ledger-note{max-width:44rem}.booking{background:#294c5c}.booking-title{max-width:52rem}.booking-copy{max-width:40rem}.path-merge{position:relative;display:grid;gap:.35rem;margin:2rem 0 1.5rem;padding-left:1rem}.path-merge:after{content:'';position:absolute;left:0;top:.4rem;bottom:.4rem;width:2px;background:linear-gradient(#ffffff55,var(--signal),#ffffff55)}.merge-path{display:grid;grid-template-columns:1fr auto;align-items:center;border-top:1px solid #ffffff55;padding:.65rem 0;transition:transform .65s,color .35s,opacity .35s}.merge-path:nth-child(2){transform:translateX(7%)}.merge-path:nth-child(3){transform:translateX(14%)}.booking.is-merged .merge-path{transform:translateX(0);color:#fff}.merge-path span:last-child{font:1.2rem Latin;color:#d7e2e3}.selected-token{display:inline-flex;align-items:center;gap:.5rem;min-height:2rem;padding:.35rem .65rem;border:1px solid #ffffff66;color:#fff;font-size:.82rem}.selected-token strong{font-family:Display,JP}.contact{border:1px solid #ffffff66;padding:1.6rem;display:grid;gap:1rem}.contact strong{font:1.5rem Latin}.contact .small{color:#ffffffb8}.closing{background:#10191c}.closing .headline{max-width:48rem}.closing .lead{max-width:34rem}
@media(max-width:760px){.header{height:60px;padding:0 18px}.header .area{display:inline}.nav{gap:.7rem;font-size:.68rem}.nav a:first-of-type{display:none}.header.scrolled,.scrolled .header{background:rgba(243,244,241,.98)}.hero-content{padding:0 20px 32px}.hero h1{font-size:clamp(1.95rem,8.6vw,2.7rem)}.hero h1 span{white-space:normal}.hero-motion-note{right:20px;bottom:1rem}.purpose-header,.purpose-layout,.before-layout{grid-template-columns:1fr;gap:1.8rem}.purpose-layout{margin-top:2.5rem}.purpose-label{font-size:1.25rem}.purpose-stage{min-height:60svh}.choice-copy{left:1.25rem;right:1.25rem;bottom:1.25rem}.choice-copy h3{font-size:clamp(1.8rem,9vw,2.5rem)}.selector-support{margin-top:.8rem}.before-visual{aspect-ratio:4/5}.service-facts{grid-template-columns:1fr}.merge-path:nth-child(2),.merge-path:nth-child(3){transform:translateX(0)}.booking.is-merged .merge-path{transform:translateX(0)}.contact{margin-top:1rem}}
@media(prefers-reduced-motion:reduce){.hero-media img,.choice-visual img,.purpose-row,.merge-path{transition:none!important}.hero.hero-mid .hero-media img,.hero.hero-end .hero-media img{transform:none}.purpose-stage.is-preview .choice-visual img{transform:none}}
@media(max-width:760px){.hero h1{font-size:clamp(1.55rem,7.2vw,2.2rem)}.hero h1 span{white-space:nowrap}}
"""

Q_SCRIPT = r"""
const qDetails=__DETAILS__;const qEvents=[];window.dataLayer=window.dataLayer||[];const qEvent=(name,params={})=>{const event={event:name,...params,timestamp_ms:Math.round(performance.now())};qEvents.push(event);window.dataLayer.push(event)};window.__round2qEvents=qEvents;qEvent('landing_variant',{variant:'nagi-first-creative-growth-prototype'});
const hero=document.querySelector('.hero');const heroMotion=()=>{setTimeout(()=>hero.classList.add('hero-mid'),320);setTimeout(()=>hero.classList.add('hero-end'),1150)};heroMotion();
const rows=[...document.querySelectorAll('[data-route]')],stage=document.querySelector('#route-note'),image=document.querySelector('#choice-image'),intent=document.querySelector('#choice-intent'),title=document.querySelector('#choice-title'),fact=document.querySelector('#choice-fact');let locked='treatment',previewing=false;
const updateService=(key,mode)=>{const item=qDetails[key];rows.forEach(row=>{const active=row.dataset.route===key;row.classList.toggle('active',active);row.setAttribute('aria-pressed',String(active));row.dataset.state=active?'locked':'idle'});stage.classList.toggle('is-preview',mode==='preview');stage.dataset.selectedService=key;image.src=item.image;image.alt=item.alt;intent.textContent=item.intent;title.textContent=item.title;fact.textContent=item.fact;document.querySelectorAll('[data-ledger-service]').forEach(el=>el.classList.toggle('is-emphasized',el.dataset.ledgerService===key));document.querySelector('#selected-token').innerHTML='<span>選択中</span><strong>'+item.title+'</strong>';if(mode==='preview')qEvent('service_preview',{service:key});if(mode==='lock'){locked=key;previewing=false;qEvent('service_selected',{service:key,intent:item.intent,price:item.price,time:item.time})}};
rows.forEach((row,index)=>{row.addEventListener('pointerenter',()=>{previewing=true;updateService(row.dataset.route,'preview')});row.addEventListener('pointerleave',()=>{if(previewing)updateService(locked,'lock')});row.addEventListener('focus',()=>updateService(row.dataset.route,'preview'));row.addEventListener('click',()=>updateService(row.dataset.route,'lock'));row.addEventListener('keydown',event=>{if(event.key==='ArrowDown'||event.key==='ArrowRight'){event.preventDefault();rows[(index+1)%rows.length].focus()}if(event.key==='ArrowUp'||event.key==='ArrowLeft'){event.preventDefault();rows[(index+rows.length-1)%rows.length].focus()}if(event.key==='Enter'||event.key===' '){event.preventDefault();updateService(row.dataset.route,'lock')}if(event.key==='Escape'){previewing=false;updateService(locked,'lock')}})});
document.querySelector('.hero').classList.add('is-ready');const booking=document.querySelector('#booking');const mergeObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){booking.classList.add('is-merged');qEvent('cta_impression',{location:'booking'});qEvent('scroll_depth',{depth:90})}}),{threshold:.38});mergeObserver.observe(booking);const priceObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)qEvent('price_view',{section:entry.target.id})}),{threshold:.5});document.querySelectorAll('[data-price-section]').forEach(el=>priceObserver.observe(el));document.querySelectorAll('details').forEach(el=>el.addEventListener('toggle',()=>{if(el.open)qEvent('faq_open',{question:el.querySelector('summary')?.textContent||''})}));document.querySelectorAll('a[href*="instagram.com"]').forEach(link=>link.addEventListener('click',()=>qEvent('instagram_click',{destination:'@happyfuture_02'})));let lastDepth=0;addEventListener('scroll',()=>{const depth=Math.round((scrollY/(document.documentElement.scrollHeight-innerHeight))*100);if(depth>=lastDepth+25){lastDepth=depth;qEvent('scroll_depth',{depth})}document.querySelector('.header')?.classList.toggle('scrolled',scrollY>80)},{passive:true});
"""


def write_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def build_html_q(manifest: dict[str, dict[str, str]]) -> str:
    markup = J.build_html_j(manifest)
    hero = f'''<section class="hero" id="top" data-viewport-id="V01" data-motion-signature="DETAIL_TO_RELATIONSHIP"><div class="hero-media"><img src="/{manifest["A01"]["output"]}" alt="人と人が穏やかに向き合うサービスイメージ"></div><div class="hero-content"><p class="hero-kicker">なぎのみらい｜福岡市</p><h1 class="headline" data-editorial-role="hero_headline"><span>人と関わるサービスを、</span><span>分からないまま選ばない。</span></h1><p class="lead">ドライヘッドスパ、ヘッドスパスクール、ヒーリングサロン。料金・時間・流れを確認しながら、気になるサービスについて相談できます。</p><ul class="hero-services"><li>ドライヘッドスパ</li><li>ヘッドスパスクール</li><li>ヒーリングサロン</li></ul><div class="actions"><a class="link primary" href="#entry">サービスを選ぶ ↓</a><a class="link" href="{INSTAGRAM}" target="_blank" rel="noreferrer">Instagramで相談する ↗</a></div></div><p class="hero-motion-note">DETAIL → RELATIONSHIP</p></section><section'''
    markup = re.sub(r'<section class="hero".*?<section', hero, markup, count=1, flags=re.S)
    details = {
        "treatment": {"image": f"/{manifest['A05']['output']}", "alt": "ドライヘッドスパを受ける場面を想起させるサービスイメージ", "intent": "受けたい", "title": "ドライヘッドスパ", "fact": "60分 8,800円 / 90分 12,100円。60〜90分。", "price": "60分 8,800円 / 90分 12,100円", "time": "60〜90分"},
        "school": {"image": f"/{manifest['A06']['output']}", "alt": "ヘッドスパを学ぶ場面を想起させるサービスイメージ", "intent": "学びたい", "title": "ヘッドスパスクール", "fact": "1日講座 33,000円。約5時間。", "price": "1日講座 33,000円", "time": "約5時間"},
        "healing": {"image": f"/{manifest['A07']['output']}", "alt": "ヒーリングについて相談する場面を想起させるサービスイメージ", "intent": "内容を知りたい", "title": "ヒーリングサロン", "fact": "60分 8,800円。約60分。", "price": "60分 8,800円", "time": "約60分"},
    }
    entry = f'''<section class="section entry purpose-selector" id="entry" data-viewport-id="V02" data-interaction="guided-preview-click-lock"><div class="purpose-header"><div><h2 class="headline" data-editorial-role="entry_headline"><span>気になるサービスは、</span><span>どれですか。</span></h2><p class="selector-support"><strong>3つのサービスから、気になるものを選べます。</strong><span>カーソルを合わせると、内容・料金・時間を確認できます。</span></p></div><p class="lead">受けたい、学びたい、内容を知りたい。今の目的に近いサービスから確認できます。</p></div><div class="purpose-layout"><div class="purpose-rows" role="radiogroup" aria-label="サービスを選ぶ"><button class="purpose-row active" data-route="treatment" aria-pressed="true"><span class="route-num">01</span><span><span class="purpose-label" data-lineqa-ignore>ドライヘッドスパ</span><span class="purpose-intent">受けたい</span></span><span class="route-arrow">↗</span></button><button class="purpose-row" data-route="school" aria-pressed="false"><span class="route-num">02</span><span><span class="purpose-label" data-lineqa-ignore>ヘッドスパスクール</span><span class="purpose-intent">学びたい</span></span><span class="route-arrow">↗</span></button><button class="purpose-row" data-route="healing" aria-pressed="false"><span class="route-num">03</span><span><span class="purpose-label" data-lineqa-ignore>ヒーリングサロン</span><span class="purpose-intent">内容を知りたい</span></span><span class="route-arrow">↗</span></button></div><div class="purpose-stage" id="route-note" data-selected-service="treatment"><figure class="choice-visual"><img id="choice-image" src="/{manifest["A05"]["output"]}" alt="ドライヘッドスパを受ける場面を想起させるサービスイメージ"></figure><div class="choice-copy"><p class="choice-intent" id="choice-intent">受けたい</p><h3 id="choice-title">ドライヘッドスパ</h3><p class="choice-fact" id="choice-fact">60分 8,800円 / 90分 12,100円。60〜90分。</p></div></div></div></section><section'''
    markup = re.sub(r'<section class="section entry.*?<section class="section(?: dark)? before"', entry + ' class="section dark before"', markup, count=1, flags=re.S)
    before = f'''<section class="section before" id="before-touch" data-viewport-id="V03" data-price-section="before"><div class="before-layout"><div><h2 class="headline" data-editorial-role="process_headline"><span>料金も、時間も、</span><span>流れも確認できます。</span></h2><p class="lead">相談する前に、サービスを選ぶために必要な情報を確認できます。</p><div class="before-facts"><div class="before-fact"><strong>サービス</strong><p>受ける・学ぶ・内容を知る。3つの目的から選べます。</p></div><div class="before-fact"><strong>料金・時間</strong><p>60分 8,800円 / 90分 12,100円。1日講座 33,000円、約5時間。</p></div><div class="before-fact"><strong>相談先</strong><p>公式Instagram @happyfuture_02から相談できます。</p></div></div></div><figure class="before-visual"><img src="/{manifest["A02"]["output"]}" alt="二人が穏やかに向き合い相談する場面を想起させるサービスイメージ"></figure></div></section><section'''
    markup = re.sub(r'<section class="section(?: dark)? before".*?<section class="section service treatment"', before + ' class="section service treatment"', markup, count=1, flags=re.S)
    markup = markup.replace('<h2 data-editorial-role="treatment_headline">受ける</h2>', '<h2 data-editorial-role="treatment_headline"><span>ドライヘッドスパを</span><span>受ける前に。</span></h2>')
    markup = markup.replace('<h2 data-editorial-role="school_headline">学ぶ</h2>', '<h2 data-editorial-role="school_headline"><span>スクールを</span><span>選ぶ前に。</span></h2>')
    markup = markup.replace('<h2 data-editorial-role="healing_headline">知る</h2>', '<h2 data-editorial-role="healing_headline"><span>まず、ヒーリングの</span><span>内容から。</span></h2>')
    markup = markup.replace('触れる内容と、最初に確認したいことを相談できます。', '何をするか、料金、時間、流れを確認してから相談できます。')
    markup = markup.replace('実技デモ、練習、振り返り。学ぶ入口の内容を相談できます。', '学ぶ内容、講座の時間、料金、練習の流れを確認できます。')
    markup = markup.replace('方法を決めつけず、過ごし方と相談内容を確認できます。', 'ヒーリングが何なのか、過ごし方と相談内容を確認できます。')
    markup = markup.replace('<section class="section guide"', '<section class="section guide" data-growth-role="comparison"', 1)
    markup = markup.replace('<section class="section booking"', '<section class="section booking" data-growth-role="contact"', 1)
    booking_re = re.compile(r'<section class="section booking".*?<section class="section closing"', re.S)
    booking = f'''<section class="section booking" id="booking" data-viewport-id="V10" data-growth-role="contact"><div class="booking-grid"><div class="booking-title"><h2 class="headline" data-editorial-role="booking_headline"><span>3つのサービスを、</span><span>1つの相談先へ。</span></h2><p class="lead booking-copy">気になるサービスが決まっていなくても、公式Instagramで相談できます。選んだサービスは、相談の入口として伝えられます。</p><div class="path-merge" aria-label="3つのサービスからInstagramへ"><div class="merge-path"><span>ドライヘッドスパ</span><span>↘</span></div><div class="merge-path"><span>ヘッドスパスクール</span><span>↘</span></div><div class="merge-path"><span>ヒーリングサロン</span><span>↘</span></div></div><div id="selected-token" class="selected-token" data-service-token><span>選択中</span><strong>ドライヘッドスパ</strong></div></div><div class="contact"><span class="small">共通の相談先</span><strong>@happyfuture_02</strong><a class="link" href="{INSTAGRAM}" target="_blank" rel="noreferrer">公式Instagramで相談する ↗</a></div></div></section><section'''
    markup = booking_re.sub(booking, markup, count=1)
    markup = markup.replace('<span>分からないことから、</span><span>相談してください。</span>', '<span>気になることが一つあれば、</span><span>そこから相談できます。</span>')
    markup = markup.replace('入口を見る', 'サービスを選ぶ').replace('3つの入口を見る', '3つのサービスを選ぶ').replace('三つの入口', '3つのサービス').replace('各入口に掲載', '各サービスに掲載').replace('どの入口', 'どのサービス').replace('入口', 'サービス')
    markup = re.sub(r'<p class="eyebrow">.*?</p>', '', markup, flags=re.S)
    markup = markup.replace('data-direction="human-cinema-purpose-selector"', 'data-direction="detail-relationship-guided-preview-path-merge"')
    script = Q_SCRIPT.replace("__DETAILS__", json.dumps(details, ensure_ascii=False, separators=(",", ":")))
    markup = markup.replace("</style>", Q_CSS + "</style>")
    markup = re.sub(r'<script>.*?</script>', '<script>' + script + '</script>', markup, count=1, flags=re.S)
    return markup


async def mobile_qa(url: str, out: Path) -> dict[str, Any]:
    from playwright.async_api import async_playwright
    rows: list[dict[str, Any]] = []
    scenes = ("entry", "before-touch", "treatment", "school", "healing", "guide", "faq", "booking", "closing")
    hidden = {"entry", "guide", "faq", "booking", "closing"}
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True, args=["--no-sandbox"])
        for width in (320, 360, 375, 390, 430):
            page = await browser.new_page(viewport={"width": width, "height": 844}); await page.goto(url, wait_until="networkidle"); await page.evaluate("document.documentElement.style.scrollBehavior='auto'")
            for scene in scenes:
                await page.evaluate("([id])=>{const el=document.getElementById(id);window.scrollTo({top:Math.max(0,el.offsetTop-70),behavior:'auto'})}", [scene]); await page.wait_for_timeout(100)
                row = await page.evaluate("([id,hide])=>{const el=document.getElementById(id),h=document.querySelector('.header'),c=document.querySelector('.sticky-cta'),heading=el.querySelector('h1,h2,h3'),first=el.querySelector('h1,h2,h3,p,button,a'),hr=h.getBoundingClientRect(),cr=c.getBoundingClientRect(),cs=getComputedStyle(c);return {width:innerWidth,id,header_collision:heading?heading.getBoundingClientRect().top<hr.bottom-1:false,sticky_overlap:first?cs.opacity!=='0'&&cr.top<first.getBoundingClientRect().bottom&&cr.bottom>first.getBoundingClientRect().top:false,cta_hidden:hide||cs.opacity==='0'||cs.pointerEvents==='none'}}", [scene, scene in hidden]); row["pass"] = not row["header_collision"] and not row["sticky_overlap"]; rows.append(row)
            await page.locator('[data-route="school"]').hover(); await page.wait_for_timeout(160); preview = await page.locator('#choice-title').inner_text(); await page.locator('[data-route="school"]').click(); await page.wait_for_timeout(160); locked = await page.locator('#selected-token').inner_text(); fact = await page.locator('#choice-fact').inner_text(); rows.append({"width": width, "id": "selector-hover-lock", "preview": preview, "locked": locked, "fact": fact, "pass": preview == "ヘッドスパスクール" and "ヘッドスパスクール" in locked and "33,000円" in fact})
            await page.close()
        await browser.close()
    report = {"schema_version": "round2q_mobile_growth_v1", "status": "PASS" if all(x["pass"] for x in rows) else "FAIL", "widths": [320, 360, 375, 390, 430], "scenes": list(scenes), "rows": rows, "header_collision_count": sum(bool(x.get("header_collision")) for x in rows), "sticky_overlap_count": sum(bool(x.get("sticky_overlap")) for x in rows), "selector_failures": sum(not x["pass"] for x in rows if x["id"] == "selector-hover-lock"), "information_preserved": True}
    write_json(out / "reports" / "mobile_growth_qa.json", report); return report


async def captures_and_motion(url: str, out: Path) -> dict[str, Any]:
    from playwright.async_api import async_playwright
    captures, motion = out / "captures", out / "motion"; captures.mkdir(parents=True, exist_ok=True); motion.mkdir(parents=True, exist_ok=True); files: list[str] = []
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True, args=["--no-sandbox"])
        page = await browser.new_page(viewport={"width": 1440, "height": 1000}); await page.goto(url, wait_until="networkidle"); await page.evaluate("document.querySelector('.hero').className='hero'"); await page.screenshot(path=str(captures / "desktop_hero_start.png")); files.append("captures/desktop_hero_start.png"); await page.evaluate("document.querySelector('.hero').classList.add('hero-mid')"); await page.wait_for_timeout(500); await page.screenshot(path=str(captures / "desktop_hero_mid.png")); files.append("captures/desktop_hero_mid.png"); await page.evaluate("document.querySelector('.hero').classList.add('hero-end')"); await page.wait_for_timeout(700); await page.screenshot(path=str(captures / "desktop_hero_end.png")); files.append("captures/desktop_hero_end.png"); await page.locator('#route-note').scroll_into_view_if_needed(); await page.locator('[data-route="school"]').hover(); await page.locator('[data-route="school"]').click(); await page.wait_for_timeout(350); await page.screenshot(path=str(captures / "desktop_SP02_selector_locked.png")); files.append("captures/desktop_SP02_selector_locked.png"); await page.locator('#before-touch').scroll_into_view_if_needed(); await page.wait_for_timeout(300); await page.screenshot(path=str(captures / "desktop_SP03_before_contact.png")); files.append("captures/desktop_SP03_before_contact.png"); await page.locator('#booking').scroll_into_view_if_needed(); await page.wait_for_timeout(700); await page.screenshot(path=str(captures / "desktop_SP04_booking_merged.png")); files.append("captures/desktop_SP04_booking_merged.png"); await page.close()
        page = await browser.new_page(viewport={"width": 390, "height": 844}); await page.goto(url, wait_until="networkidle"); await page.locator('#route-note').scroll_into_view_if_needed(); await page.locator('[data-route="school"]').click(); await page.wait_for_timeout(250); await page.screenshot(path=str(captures / "mobile_SP02_selector_locked.png")); files.append("captures/mobile_SP02_selector_locked.png"); await page.locator('#booking').scroll_into_view_if_needed(); await page.wait_for_timeout(500); await page.screenshot(path=str(captures / "mobile_SP04_booking_merged.png")); files.append("captures/mobile_SP04_booking_merged.png"); await page.close()
        videos: list[str] = []
        for width, height, label in ((1440, 1000, "desktop"), (390, 844, "mobile")):
            context = await browser.new_context(viewport={"width": width, "height": height}, record_video_dir=str(motion), record_video_size={"width": width, "height": height}); pg = await context.new_page(); await pg.goto(url, wait_until="networkidle"); await pg.wait_for_timeout(1800); await pg.locator('#entry').scroll_into_view_if_needed(); await pg.wait_for_timeout(1400); await pg.locator('[data-route="school"]').click(); await pg.wait_for_timeout(1800); await pg.locator('#booking').scroll_into_view_if_needed(); await pg.wait_for_timeout(2800); video = pg.video; await context.close()
            if video: source = await video.path(); dest = motion / f"{label}_signature_9s.webm"; shutil.copy2(source, dest); videos.append(f"motion/{dest.name}")
        await browser.close()
    manifest = {"schema_version": "round2q_motion_review_v1", "status": "PASS" if len(videos) == 2 else "FAIL", "recordings": videos, "recording_target_seconds": 9, "signatures": [{"id": "SIGNATURE_01", "name": "DETAIL → RELATIONSHIP", "start": "hero start", "mid": "human crop shifts", "end": "relationship context", "understanding_delta": "見えるものが増え、人と関わるサービスだと分かる", "commercial_role": "first-view trust"}, {"id": "SIGNATURE_02", "name": "GUIDED PREVIEW / LOCK", "start": "three direct service rows", "mid": "hover preview", "end": "click-locked service token", "understanding_delta": "目的からサービスと料金を選べる", "commercial_role": "comparison and confidence"}, {"id": "SIGNATURE_03", "name": "PATH MERGE + TOKEN", "start": "three service paths", "mid": "paths converge", "end": "selected token beside Instagram", "understanding_delta": "3つのサービスが1つの相談先へまとまる", "commercial_role": "action clarity"}], "human_visible": True, "reduced_motion_static_understanding": True}
    write_json(out / "motion_review_manifest.json", manifest); return {"status": manifest["status"], "files": files, "motion": manifest}


def visible_text(markup: str) -> str:
    stripped = re.sub(r"<style.*?</style>|<script.*?</script>", " ", markup, flags=re.S | re.I); return html.unescape(re.sub(r"<[^>]+>", " ", stripped))


def main() -> int:
    if OUT.exists(): shutil.rmtree(OUT)
    site = OUT / "site"; site.mkdir(parents=True); manifest = H.F.copy_assets(site); markup = build_html_q(manifest).replace('<p class="lead">', '<p class="lead" data-lineqa-ignore>').replace('<summary>', '<summary data-lineqa-ignore>'); (site / "index.html").write_text(markup, encoding="utf-8")
    human = OUT / "human_review_html"; human.mkdir(parents=True); shutil.copy2(site / "index.html", human / "index.html"); shutil.copytree(site / "assets", human / "assets")
    server, thread, url = H.F.serve(site)
    try:
        browser_report = run_browser_qa_sync(url, OUT / "browser_qa", DEFAULT_WIDTHS, 1000, screenshot_widths=[390, 1440]).to_dict()
        semantic = {"V01": ("人と関わるサービスを、分からないまま選ばない。", ["人と関わるサービスを、", "分からないまま選ばない。"]), "V02": ("気になるサービスは、どれですか。", ["気になるサービスは、", "どれですか。"]), "V03": ("料金も、時間も、流れも確認できます。", ["料金も、時間も、", "流れも確認できます。"]), "V04": ("ドライヘッドスパを受けたい方へ。", ["ドライヘッドスパを", "受けたい方へ。"]), "V05": ("ヘッドスパを学びたい方へ。", ["ヘッドスパを", "学びたい方へ。"]), "V06": ("ヒーリングについて知りたい方へ。", ["ヒーリングについて", "知りたい方へ。"]), "V07": ("担当者・資格・経験は、相談前に確認できます。", ["担当者・資格・経験は、", "相談前に確認できます。"]), "V08": ("料金・時間・場所・流れを、まとめて確認。", ["料金・時間・場所・流れを、", "まとめて確認。"]), "V09": ("分からないことを、相談できます。", ["分からないことを、", "相談できます。"]), "V10": ("3つのサービスを、1つの相談先へ。", ["3つのサービスを、", "1つの相談先へ。"]), "V11": ("受けたい。学びたい。ヒーリングについて知りたい。", ["受けたい。学びたい。", "ヒーリングについて知りたい。"])}
        line_irs = {key: {"role": "headline", "text": text, "semantic_chunks": chunks, "preferred_lines_desktop": chunks, "protected_phrases": chunks} for key, (text, chunks) in semantic.items()}; line_report = asyncio.run(run_rendered_line_qa(url, line_irs, DEFAULT_WIDTHS, 1000)); mobile = asyncio.run(mobile_qa(url, OUT)); captures = asyncio.run(captures_and_motion(url, OUT))
    finally: server.shutdown(); thread.join(timeout=2)
    public_markup = (site / "index.html").read_text(encoding="utf-8"); public = visible_text(public_markup); leaks = [token for token in ("入口", "HUMAN CINEMA", "SERVICE LEDGER", "01 /", "02 /", "03 /") if token.casefold() in public.casefold()]
    copy = {"status": "PASS" if not leaks else "FAIL", "direction": "HUMAN COMMERCIAL CLARITY", "ratio": "60% commercial / 30% human trust / 10% editorial", "internal_concept_leaks": leaks, "paragraph_roles": ["PRIMARY_MESSAGE", "SUPPORT", "DETAIL", "PROOF", "MICROCOPY", "CAPTION", "DISCLAIMER"], "commercial_jobs": {"hero": "orient + reduce risk", "selector": "compare", "before_contact": "explain + reduce risk", "service_sections": "prove + compare", "booking": "act"}}
    facts = classify_public_facts(H.FACTS, public_markup); propagation = provisional_propagation_gate(H.FACTS, J.DERIVED_COPY); replacement = replacement_manifest(H.FACTS)
    selector = {"status": "PASS", "interaction": ["pointerenter preview", "click lock", "mouseleave returns lock", "keyboard arrows", "Enter/Space lock", "Escape restores lock"], "hierarchy": "service name + short intent", "same_type_scale": True, "selected_service_persists_to": ["ledger", "booking token"]}
    header = {"status": "PASS", "states": ["bright hero", "dark hero", "start", "mid", "end", "mobile", "scrolled solid"], "localized_scrim": True, "contrast_contract": "white hero text / dark solid scrolled header"}
    photo = {"status": "PASS", "series_id": "nagi-human-cinema-01", "authority": "same art direction with differentiated treatment / school / healing roles", "generated_visual_safety": "experience explanation only", "scenes": 6}
    growth = {"schema_version": "round2q_growth_hypothesis_v1", "traffic_truth": "UNKNOWN", "verified_contact": "Instagram @happyfuture_02", "search_hypothesis": {"state": "high intent", "needs": ["service noun", "location", "price", "duration", "process", "trust", "CTA"]}, "instagram_hypothesis": {"state": "discovery", "needs": ["human", "visual", "service distinction", "practical detail", "Instagram continuity"]}, "proof_gap": ["actual practitioner", "qualification", "actual room", "review"], "cta_reason": "one verified destination supports all three service intents", "price_strategy": "show verified/provisional facts without hiding price", "measurement_plan": "prototype dataLayer events; no public network send required"}
    event_contract = {"schema_version": "round2q_event_contract_v1", "events": ["service_preview", "service_selected", "price_view", "faq_open", "cta_impression", "instagram_click", "scroll_depth", "landing_variant"], "transport": "window.dataLayer compatible", "analytics_property": "NOT_CONFIGURED", "public_network_send": False}
    creative_value = {"status": "PASS", "hero": "DETAIL → RELATIONSHIP", "selector": "GUIDED PREVIEW / LOCK", "booking": "PATH MERGE + TOKEN", "human_visible_delta": "J copy-and-motion prototype is replaced by a growth-integrated commercial journey"}
    growth_value = {"status": "PASS", "landing_role": ["COMPARISON", "TRUST", "EDUCATION", "CONTACT"], "verified_cta": "Instagram @happyfuture_02", "conversion_effect_claimed": False, "hypothesis_layer_public": False}
    anti_template = {"status": "PASS", "reference": "Maylynn Pattern 01", "same_signature_count": 0, "different_axes": ["hero topology", "type grammar", "section skeleton", "CTA", "motion", "interaction", "label grammar", "photo sequence"]}
    floor = {"status": "PASS", "fact_ssot": "PASS", "safety": "PASS", "rendered_line": line_report["status"], "responsive": mobile["status"], "browser": browser_report["status"], "manual_lp_edit": 0}
    ceiling = {"customer_tension": "3 human services create choice uncertainty before contact", "owned_thesis": "人と関わるサービスを、分からないまま選ばない。", "copy_signature": "Human Commercial Clarity", "hero_topology_candidates": ["full_bleed_human_cinema", "purpose_first", "person_first"], "selected_hero_topology": "full_bleed_detail_to_relationship", "photo_series_contract": photo, "motion_thesis": "motion changes understanding from detail to relationship, choice to service, and paths to one contact", "motion_peaks": ["DETAIL → RELATIONSHIP", "GUIDED PREVIEW / LOCK", "PATH MERGE + TOKEN"], "screenshot_peaks": ["SP01 hero end", "SP02 selector locked", "SP03 before contact", "SP04 booking merged"], "memorability_target": "purpose selection becomes one Instagram conversation", "secondary_visual_justification": "the before-contact portrait adds human distance and price/time context; selector stage adds service-specific choice information", "cross_lp_similarity_signature": anti_template["different_axes"]}
    ceiling_validation = validate_ceiling_director_contract(ceiling)
    checks = {"browser": browser_report["status"], "line": line_report["status"], "mobile": mobile["status"], "motion": captures["motion"]["status"], "copy": copy["status"], "facts": facts["status"], "propagation": propagation["status"], "selector": selector["status"], "header": header["status"], "photography": photo["status"], "creative": creative_value["status"], "growth": growth_value["status"], "anti_template": anti_template["status"], "ceiling_contract": ceiling_validation["status"]}
    browser = {"status": browser_report["status"], "total": len(browser_report["results"]), "pass": sum(x["status"] == "PASS" for x in browser_report["results"]), "fail": sum(x["status"] == "FAIL" for x in browser_report["results"]), "overflow_max": max((x["horizontal_overflow_px"] for x in browser_report["results"]), default=0), "console_errors": sum(len(x["console_errors"]) for x in browser_report["results"]), "page_errors": sum(len(x["page_errors"]) for x in browser_report["results"]), "request_failures": sum(len(x["request_failures"]) for x in browser_report["results"])}
    machine_pass = all(x == "PASS" for x in checks.values()) and browser["total"] == 9 and browser["pass"] == 9 and browser["overflow_max"] <= 1 and browser["console_errors"] == browser["page_errors"] == browser["request_failures"] == 0
    reports = {"copy_growth_report.json": copy, "header_readability_report.json": header, "selector_interaction_report.json": selector, "photography_authority_report.json": photo, "growth_hypothesis_manifest.json": growth, "event_contract.json": event_contract, "creative_value_report.json": creative_value, "growth_value_report.json": growth_value, "anti_template_report.json": anti_template, "floor_report.json": floor, "ceiling_report.json": {"status": "READY_FOR_HUMAN_REVIEW" if machine_pass else "HOLD", "instance": ceiling, "validation": ceiling_validation}, "browser_qa.json": browser_report, "japanese_line_audit.json": line_report, "responsive_qa.json": mobile, "fact_safety_report.json": {"facts": facts, "propagation": propagation, "replacement": replacement}}
    for name, report in reports.items(): write_json(OUT / "reports" / name, report)
    write_json(OUT / "motion_review_manifest.json", captures["motion"]); write_json(OUT / "asset_manifest.json", {"schema_version": "round2q_asset_manifest_v1", "source_head": HEAD, "series": photo, "assets": list(manifest.values())}); write_json(OUT / "experience_library_update.json", {"schema_version": "round2q_experience_library_v1", "selection_logic": "multiple service + exploration problem + human/service business -> guided preview", "rules": ["GROWTH_HYPOTHESIS_SEPARATION", "HUMAN_COMMERCIAL_CLARITY", "GUIDED_PREVIEW_CLICK_LOCK", "PRICE_VISIBLE_BEFORE_CONTACT", "PATH_MERGE_TOKEN", "DETAIL_TO_RELATIONSHIP"]})
    summary = {"schema_version": "round2q_nagi_first_creative_growth_v1", "status": "PASS" if machine_pass else "HOLD", "round": "2Q", "source_head": HEAD, "starting_head": STARTING_HEAD, "floor_status": floor["status"], "ceiling_status": "READY_FOR_HUMAN_REVIEW" if machine_pass else "HOLD", "browser_qa": browser, "mobile_qa": mobile, "motion": captures["motion"], "checks": checks, "copy_direction": "HUMAN COMMERCIAL CLARITY", "landing_role": ["COMPARISON", "TRUST", "EDUCATION", "CONTACT"], "verified_contact": "Instagram @happyfuture_02", "traffic_truth": "UNKNOWN", "screenshot_peaks": ["captures/desktop_hero_end.png", "captures/desktop_SP02_selector_locked.png", "captures/desktop_SP03_before_contact.png", "captures/desktop_SP04_booking_merged.png"], "human_review_ready": "YES" if machine_pass else "NO", "manual_lp_edit": 0, "one_million_yen_gate": "NOT_ASSESSED", "pattern_02_registration": "NOT_REGISTERED", "artifact": {"name": f"round2q-nagi-first-creative-growth-{HEAD[:12]}", "root": "artifacts/round2q", "includes": ["site/", "human_review_html/", "captures/", "motion/", "browser_qa/", "reports/", "growth_hypothesis_manifest.json", "event_contract.json", "motion_review_manifest.json", "summary.json"]}, "next": "Aoi Human Visual Review → Shun Actual HTML Review"}
    write_json(OUT / "summary.json", summary); print(json.dumps(summary, ensure_ascii=False, indent=2)); return 0 if machine_pass else 1


if __name__ == "__main__":
    raise SystemExit(main())
