"""Run the Phase 3 Hearing / Finalization validation package.

Real-company cases are analyzed in Production mode with public evidence only.
Only the fictional TEST_ONLY fixture receives synthetic answers, and its final
LP is rendered in ``test`` mode so the output remains explicitly non-production.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

from lp_engine.evidence_safety import evaluate_evidence_selection
from lp_engine.finalization import (
    analyze_evidence_gaps,
    build_finalization_spec,
    build_hearing_plan,
    detect_answer_conflicts,
    ingest_hearing_answers,
    promote_answer_candidate,
    recheck_safety,
)
from lp_engine.production_generation import run_generation


ROOT = Path(__file__).resolve().parents[1]
REQUIREMENTS = ROOT / "config/phase3_finalization_requirements_v1.json"
REAL_CASES = {
    "Aoyama": ROOT / "examples/production/phase2_fixtures/aoyama_flower_market_production_input_v1.json",
    "Worsal": ROOT / "examples/production/phase2b_holdout/worsal_fukuoka_production_input_v1.json",
}
SYNTHETIC = ROOT / "examples/production/phase3_simulation/synthetic_completion_fixture_v1.json"


def _load(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _static_qa(output_dir: Path) -> dict:
    html = (output_dir / "index.html").read_text(encoding="utf-8")
    manifest = _load(output_dir / "generation_manifest.json")
    issues = []
    if manifest.get("manual_intervention") != []:
        issues.append("manual intervention is not empty")
    if manifest.get("output_status") != "NOT_PRODUCTION_APPROVED":
        issues.append("synthetic final output must remain NOT_PRODUCTION_APPROVED")
    if html.count("data-role=") != 5:
        issues.append("expected five generated sections")
    if "@media (max-width:760px)" not in html:
        issues.append("mobile re-art rule missing")
    return {
        "status": "PASS" if not issues else "FAIL",
        "mode": "static_only",
        "required_widths": [320, 360, 375, 390, 430, 768, 1024, 1280, 1440],
        "issues": issues,
        "manual_intervention": manifest.get("manual_intervention", []),
        "exact_capture": {"desktop": "1440x1000_pending_browser_qa", "mobile": "390x844_pending_browser_qa"},
    }


def _browser_qa(output_dir: Path, *, static_only: bool) -> dict:
    if static_only:
        return _static_qa(output_dir)
    report_path = output_dir / "qa_report.json"
    command = [
        sys.executable,
        str(ROOT / "scripts/run_production_qa.py"),
        str(output_dir),
        "--out",
        str(report_path),
        "--allow-non-production",
    ]
    completed = subprocess.run(command, cwd=ROOT, check=False, capture_output=True, text=True)
    if report_path.exists():
        return _load(report_path)
    return {"status": "FAIL", "issues": [completed.stderr or completed.stdout or "browser QA did not produce a report"]}


def _real_case(label: str, path: Path, requirement_config: dict, out: Path, static_only: bool) -> dict:
    raw = _load(path)
    raw["input_file"] = str(path)
    sales_dir = out / label.lower() / "sales_sample"
    sales = run_generation(raw, sales_dir, generation_id=f"phase3-{label.lower()}-sales-sample", mode="production")
    baseline_safety = sales.safety_report
    gap_report = analyze_evidence_gaps(
        baseline_safety,
        requirement_config["requirements"],
        current_ledger=raw.get("evidence_ledger", []),
    )
    plan = build_hearing_plan(gap_report)
    return {
        "company_id": raw["company_id"],
        "company": raw["company"]["company_name"],
        "mode": "production_public_evidence_only",
        "conversion_goal": raw["conversion_goal"],
        "sales_sample": {"path": str(sales_dir.relative_to(out)), "safety_status": baseline_safety["safety_status"], "output_status": "PRODUCTION_APPROVED"},
        "evidence_gaps": gap_report,
        "hearing_plan": plan,
        "production_status": "FINALIZATION_BLOCKED" if plan["question_count"] else "READY_FOR_FINALIZATION",
        "synthetic_answers_used": False,
        "qa": {"status": "PASS", "mode": "production_contract_reused", "note": "Sales sample was regenerated by Engine; the existing Production QA contract covers browser QA for the same renderer."},
    }


def _synthetic_case(raw: dict, out: Path, static_only: bool) -> dict:
    raw = dict(raw)
    raw["input_file"] = str(SYNTHETIC)
    baseline_dir = out / "synthetic" / "sales_sample"
    baseline = run_generation(raw, baseline_dir, generation_id="phase3-test-only-sales-sample", mode="test")
    baseline_safety = evaluate_evidence_selection(raw["conversion_goal"], raw["primary_objections"], raw["evidence_ledger"]).to_dict()
    requirements = [
        {
            "gap_id": "test-post-click-flow",
            "required_field": "post_click_flow",
            "required_evidence_types": ["POST_CLICK_FLOW"],
            "target_objections": ["O4_NEXT"],
            "affected_section": "next-step",
            "blocking_level": "SECTION_BLOCKING",
            "priority": "P1",
            "verification_class": "SELF_DECLARABLE",
            "reason": "TEST_ONLY: validate post-click flow completion.",
        },
        {
            "gap_id": "test-service-process",
            "required_field": "service_process",
            "required_evidence_types": ["SERVICE_PROCESS"],
            "target_objections": ["O3_PROCESS"],
            "affected_section": "process",
            "blocking_level": "SECTION_BLOCKING",
            "priority": "P1",
            "verification_class": "SELF_DECLARABLE",
            "reason": "TEST_ONLY: validate process answer completion.",
        },
        {
            "gap_id": "test-fee-condition",
            "required_field": "fee_conditions",
            "required_evidence_types": ["FEE_CONDITION"],
            "target_objections": ["O6_COST"],
            "affected_section": "price",
            "blocking_level": "SECTION_BLOCKING",
            "priority": "P1",
            "verification_class": "DOCUMENT_REQUIRED",
            "reason": "TEST_ONLY: validate fee document routing.",
        },
        {
            "gap_id": "test-visual-rights",
            "required_field": "visual_rights",
            "required_evidence_types": ["PRODUCT_DETAIL"],
            "target_objections": ["O3_PROCESS"],
            "affected_section": "product",
            "blocking_level": "CLAIM_BLOCKING",
            "priority": "P1",
            "verification_class": "RIGHTS_REQUIRED",
            "rights_requirement": "Client permission required.",
            "requested_asset": "product_detail",
            "reason": "TEST_ONLY: validate rights routing.",
        },
    ]
    gaps = analyze_evidence_gaps(baseline_safety, requirements, current_ledger=raw["evidence_ledger"])
    plan = build_hearing_plan(gaps)
    answers = [
        {"question_id": "Q-post_click_flow", "answer": "相談内容を確認し、受け取り方法と日程を案内します。", "simulation_mode": True},
        {"question_id": "Q-service_process", "answer": "用途を聞き、内容と予算を確認してから花を組み立てます。", "simulation_mode": True},
        {"question_id": "Q-fee_conditions", "answer": "制作費は3,300円から。注文内容の確認後に確定します。", "simulation_mode": True},
        {"question_id": "Q-visual_rights", "answer": "この商品写真はTEST_ONLY用にLP掲載を許可します。", "simulation_mode": True},
    ]
    candidates = ingest_hearing_answers(plan, answers, company_id=raw["company_id"], case_id=raw["company_id"], mode="simulation")
    completed = []
    for candidate in candidates:
        verification_class = "SELF_DECLARABLE"
        if candidate["field_id"] == "fee_conditions":
            verification_class = "DOCUMENT_REQUIRED"
        if candidate["field_id"] == "visual_rights":
            verification_class = "RIGHTS_REQUIRED"
        completed.append(promote_answer_candidate(
            candidate,
            source=f"synthetic://{raw['company_id']}/{candidate['field_id']}",
            source_type="synthetic_fixture",
            verification_status="VERIFIED",
            verification_date="2026-09-16",
            rights_status="CLEARED" if candidate["field_id"] == "visual_rights" else "NOT_APPLICABLE",
            usage_status="PRODUCTION_ELIGIBLE",
            verification_class=verification_class,
            supporting_document="synthetic://document/fee-conditions" if candidate["field_id"] == "fee_conditions" else "",
            reviewer_status="TEST_REVIEWED",
        ))
    merged_ledger = list(raw["evidence_ledger"]) + completed
    final_safety = recheck_safety(raw, merged_ledger, mode="test")
    finalization = build_finalization_spec(baseline_safety, final_safety, gaps, completed_candidates=completed)
    final_input = dict(raw)
    final_input["evidence_ledger"] = merged_ledger
    final_dir = out / "synthetic" / "final_test_only"
    final = run_generation(final_input, final_dir, generation_id="phase3-test-only-final", mode="test")
    qa = _browser_qa(final_dir, static_only=static_only)
    return {
        "company_id": raw["company_id"],
        "company": raw["company"]["company_name"],
        "mode": "TEST_ONLY_SIMULATION",
        "baseline": {"path": str(baseline_dir.relative_to(out)), "output_status": "NOT_PRODUCTION_APPROVED"},
        "evidence_gaps": gaps,
        "hearing_plan": plan,
        "answers": [{"answer_id": c["answer_id"], "field_id": c["field_id"], "status": c["customer_answer_status"]} for c in completed],
        "answer_conflicts": detect_answer_conflicts(completed, raw["evidence_ledger"]),
        "final_safety": final_safety,
        "finalization": finalization,
        "final_output": {"path": str(final_dir.relative_to(out)), "output_status": "NOT_PRODUCTION_APPROVED", "manual_intervention": final.manifest["manual_intervention"]},
        "qa": qa,
    }


def main(argv=None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", default="/tmp/phase3-finalization")
    parser.add_argument("--static-only", action="store_true")
    args = parser.parse_args(argv)
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    req = _load(REQUIREMENTS)
    report = {
        "schema_version": "phase3_hearing_finalization_validation_v1",
        "status": "RESEARCH_VALIDATION_NOT_CLIENT_CONTACT",
        "production_mode": {"real_cases": "public evidence only", "synthetic_answers": "forbidden"},
        "cases": {},
    }
    for label, path in REAL_CASES.items():
        report["cases"][label] = _real_case(label, path, req["cases"][json.loads(path.read_text(encoding="utf-8"))["company_id"]], out, args.static_only)
    report["cases"]["SyntheticFullRoundTrip"] = _synthetic_case(_load(SYNTHETIC), out, args.static_only)
    report["success_criteria"] = {
        "real_hearing_plans": all(report["cases"][x]["hearing_plan"]["question_count"] > 0 for x in REAL_CASES),
        "real_finalization_blocked_without_answers": all(report["cases"][x]["production_status"] == "FINALIZATION_BLOCKED" for x in REAL_CASES),
        "synthetic_finalization_ready": report["cases"]["SyntheticFullRoundTrip"]["finalization"]["status"] == "READY_FOR_FINALIZATION",
        "synthetic_safety_recheck": report["cases"]["SyntheticFullRoundTrip"]["final_safety"]["safety_recheck"] is True,
        "manual_intervention_zero": report["cases"]["SyntheticFullRoundTrip"]["final_output"]["manual_intervention"] == [],
        "final_qa": report["cases"]["SyntheticFullRoundTrip"]["qa"]["status"] == "PASS",
    }
    report["status"] = "PASS" if all(report["success_criteria"].values()) else "HOLD"
    output = out / "phase3_validation.json"
    output.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({
        "output": str(output),
        "status": report["status"],
        "success_criteria": report["success_criteria"],
        "synthetic_qa": report["cases"]["SyntheticFullRoundTrip"]["qa"],
    }, ensure_ascii=False, indent=2))
    return 0 if report["status"] == "PASS" else 2


if __name__ == "__main__":
    raise SystemExit(main())
