"""Round 3K: integrate final persuasion copy and choice-linked media into F3."""
from __future__ import annotations
import asyncio, hashlib, json, shutil, sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]/"scripts"))
import run_round3i_br_f3_full_page as f3  # noqa: E402

ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/"artifacts/round3k_nagi_persuasion_media"; f3.OUT=OUT
IG="https://www.instagram.com/happyfuture_02/"

CSS=f3.CSS+r'''
.stage-media{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;opacity:.38;mix-blend-mode:multiply;filter:saturate(.68) contrast(.94);transition:opacity .35s,transform .5s}.choice-stage{isolation:isolate}.choice-stage:before{z-index:1}.choice-stage>*{z-index:2}.stage-media-wrap{position:absolute;inset:0;overflow:hidden}.stage-media-wrap .visual-disclosure{position:absolute;right:26px;bottom:24px;z-index:4}.choice-stage>div,.choice-stage>a{z-index:3}.depth-note{max-width:520px;color:#425650;line-height:2}.trust .lead{max-width:450px}.action-examples{display:grid;gap:14px;margin-top:32px}.action-example{border-left:2px solid var(--gold);padding:10px 16px;color:#425650}.service-copy{white-space:pre-line}.ending h2{max-width:720px}
@media(max-width:760px){.stage-media{opacity:.28}.stage-media-wrap .visual-disclosure{right:18px;bottom:18px}.choice-stage{min-height:430px}.choice-stage h3{font-size:43px}.choice-head h2{font-size:33px!important}.hero .copy h1{font-size:30px!important}.middle .copy h2{font-size:32px!important}.depth-note{font-size:14px}.action-example{font-size:14px}.ending h2{max-width:330px}}
'''

HTML=f3.HTML
HTML=HTML.replace('assets/photography/nagi_no_mirai/','assets/photography/generated/nagi_no_mirai/')
HTML=HTML.replace('<div class="copy"><div class="kicker">なぎのみらい / 福岡市</div><h1><span class="line-chunk">今の自分に近い</span><br><span class="line-chunk">入口から選ぶ。</span></h1><p>ドライヘッドスパ、ヘッドスパスクール、ヒーリングサロン。目的の違う3つのサービスを、内容から確認できます。</p></div>', '<div class="copy"><div class="kicker">なぎのみらい｜福岡市</div><h1><span class="line-chunk">休みたい日もあれば、</span><br><span class="line-chunk">もっと知りたくなる日もある。</span></h1><p>なぎのみらいには、<br>ドライヘッドスパ、ヘッドスパスクール、<br>ヒーリングサロンがあります。<br><br>受ける・学ぶ・知る ↓</p></div>')
HTML=HTML.replace('<div class="choice-head"><div class="copy"><div class="kicker">01 / CHOOSE</div><h2><span class="line-chunk">気になるものを、</span><br><span class="line-chunk">ひとつ選ぶ。</span></h2></div><p>今の目的に近い入口を選ぶと、次に確認したいことが見えてきます。</p></div>', '<div class="choice-head"><div class="copy"><div class="kicker">02 / 選ぶ</div><h2><span class="line-chunk">今したいことから、</span><br><span class="line-chunk">サービスを選ぶ。</span></h2></div><p>受ける・学ぶ・知る。<br>今の自分に近いものから、内容を見ていけます。</p></div>')
HTML=HTML.replace('<article class="choice-stage"><div><div class="kicker" style="color:#e4bd8b" id="stage-kind">01 / RECEIVE</div><h3 id="stage-title">ドライヘッド<br>スパ</h3><p id="stage-copy">施術について、気になる内容を確認したい方の入口です。</p></div><a href="#middle">この入口の先を見る ↓</a></article>', '<article class="choice-stage"><div class="stage-media-wrap"><img id="stage-media" class="stage-media" src="assets/photography/generated/nagi_no_mirai/welcome_human.png" alt="" aria-hidden="true"><span id="stage-disclosure" class="visual-disclosure">イメージ</span></div><div><div class="kicker" style="color:#e4bd8b" id="stage-kind">01 / 受ける</div><h3 id="stage-title">ドライヘッド<br>スパ</h3><p id="stage-copy" class="service-copy"></p></div><a href="#middle">このサービスを読む ↓</a></article>')
HTML=HTML.replace('<section class="section middle" id="middle"><div class="wrap"><div class="copy"><div class="kicker">02 / FEEL THE DIFFERENCE</div><h2><span class="line-chunk">触れる前に、</span><br><span class="line-chunk">感じ取る。</span></h2><p>光が面を渡り、距離が少しひらく。選んだサービスの世界を、急がずに知るための時間です。</p></div></div><div class="material-caption"><b>光と距離</b>surface / light / distance</div></section>', '<section class="section middle" id="middle"><div class="wrap"><div class="copy"><div class="kicker" id="depth-kind">03 / 受ける</div><h2 id="depth-title"><span class="line-chunk">選んだサービスを、</span><br><span class="line-chunk">内容から読む。</span></h2><p id="depth-copy" class="depth-note"></p></div></div><div class="material-caption"><b>選んだサービスから読む</b>purpose / detail / next step</div></section>')
old_trust='<section class="section trust" id="trust"><div class="wrap trust-grid"><div class="copy"><div class="kicker" style="color:#e4bd8b">03 / KNOW</div><h2><span class="line-chunk">分かることを、</span><br><span class="line-chunk">分かる形で。</span></h2><p class="lead">公開されている情報の範囲で、サービスの区分・場所・連絡先を整理しています。</p></div><div class="fact-stream"><div class="fact"><b>SERVICE</b><span>ドライヘッドスパ / ヘッドスパスクール / ヒーリングサロン</span></div><div class="fact"><b>LOCATION</b><span>福岡市</span></div><div class="fact"><b>CONTACT</b><span>公式Instagram @happyfuture_02</span></div><div class="fact"><b>BOUNDARY</b><span>料金・時間・個別の内容は、公式Instagramで確認・相談できます。</span></div></div></div></section>'
new_trust='<section class="section trust" id="trust"><div class="wrap trust-grid"><div class="copy"><div class="kicker" style="color:#e4bd8b">06 / 確認する</div><h2><span class="line-chunk">確認できること</span></h2><p class="lead">ここで分かること。<br>まだ、分からないこと。</p></div><div class="fact-stream"><div class="fact"><b>分かっていること</b><span>福岡市<br>ドライヘッドスパ<br>ヘッドスパスクール<br>ヒーリングサロン<br>公式Instagram @happyfuture_02</span></div><div class="fact"><b>まだ分からないこと</b><span>料金<br>時間<br>個別の内容</span></div></div></div></section>'
HTML=HTML.replace(old_trust,new_trust)
old_contact='<section class="section contact" id="contact"><div class="wrap contact-grid"><div class="copy"><div class="kicker">04 / CONTACT</div><h2><span class="line-chunk">決めきれないときは、</span><br><span class="line-chunk">入口から伝える。</span></h2><div class="path"><div class="path-step"><b>01</b><span>気になるサービスを選ぶ</span></div><div class="path-step"><b>02</b><span>確認したいことを整理する</span></div><div class="path-step"><b>03</b><span>公式Instagramで相談する</span></div></div></div><aside class="contact-card"><div class="kicker">OFFICIAL CONTACT</div><p>受ける・学ぶ・内容を知る。どの入口からでも、相談先は同じです。</p><a href="%%IG%%" target="_blank" rel="noopener">@happyfuture_02 ↗</a></aside></div></section>'
new_contact='<section class="section contact" id="contact"><div class="wrap contact-grid"><div class="copy"><div class="kicker">07 / 連絡する前に</div><h2><span class="line-chunk">最初の一文に、</span><br><span class="line-chunk">迷ったら。</span></h2><p>たとえば、こんな書き方があります。</p><div class="action-examples"><div class="action-example">「ドライヘッドスパについて聞きたいです」</div><div class="action-example">「スクールについて知りたいです」</div><div class="action-example">「ヒーリングについて、内容を確認したいです」</div></div><p class="public-note">これは、文面の例です。実際には、自分が確かめたいことに置き換えてください。</p></div><aside class="contact-card"><div class="kicker">MESSAGE</div><p>選んだサービス名から、確かめたいことを一つ書けます。</p></aside></div></section>'
HTML=HTML.replace(old_contact,new_contact)
HTML=HTML.replace('<div class="kicker">05 / LEAVE ROOM</div><h2><span class="line-chunk">分かることが増えたら。</span><br><span class="line-chunk">相談していい。</span></h2><p>確認できたことと、聞いてみたいこと。その両方を持ったまま、次の一歩へ進めます。</p>', '<div class="kicker">S7 / 最初の一文</div><h2><span class="line-chunk">確かめたいことを、</span><br><span class="line-chunk">一つ書く。</span></h2><p>受ける・学ぶ・知る。選んだサービス名から書き始めれば、確認したいことを伝えられます。</p>')
HTML=HTML.replace('<div class="kicker">なぎのみらい / 福岡市</div><h2><span class="line-chunk">気になることがあれば。</span><br><span class="line-chunk">そこから相談できます。</span></h2><p>サービスの内容を見て、まだ決めきれないことがあれば。今の目的に近いことを公式Instagramからお聞かせください。</p><a href="%%IG%%" target="_blank" rel="noopener">Instagramで相談する ↗</a>', '<div class="kicker">なぎのみらい｜公式Instagram</div><h2><span class="line-chunk">ここまで読んで、</span><br><span class="line-chunk">ひとつ確かめたい</span><br><span class="line-chunk">ことが残ったら。</span></h2><p>なぎのみらいの連絡先は、公式Instagramです。</p><p><strong>@happyfuture_02</strong></p><a href="%%IG%%" target="_blank" rel="noopener">公式Instagramを開く ↗</a>')
HTML=HTML.replace('Instagram ↗','公式Instagram ↗')

JS='''<script>const data={treatment:{kind:'01 / 受ける',title:'ドライヘッド<br>スパ',copy:'一日が終わっても、\\n頭の中だけ切り替わらない日がある。\\n\\nもう何かをするより、\\n何もしない時間がほしい。\\n\\nドライヘッドスパを探すのは、\\nそんな日かもしれません。',media:'assets/photography/generated/nagi_no_mirai/welcome_human.png',disclosure:'イメージ',depthTitle:['一日が終わっても、','頭の中だけ切り替わらない日がある。'],depthCopy:'もう何かをするより、\\n何もしない時間がほしい。\\n\\nドライヘッドスパを探すのは、\\nそんな日かもしれません。'},school:{kind:'02 / 学ぶ',title:'ヘッドスパ<br>スクール',copy:'ヘッドスパを見ていて、\\n「どうやっているんだろう」が残ったら。\\n\\nヘッドスパを知るうちに、\\n技術そのものにも目が向く。\\n\\nなぎのみらいには、\\nヘッドスパスクールもあります。\\n\\nカリキュラムや受講条件は、\\nこのページでは確認できていません。',media:'assets/photography/generated/nagi_no_mirai/school_learning_context.png',disclosure:'イメージ',depthTitle:['「どうやっているんだろう」が','残ったら。'],depthCopy:'ヘッドスパを知るうちに、\\n技術そのものにも目が向く。\\n\\nカリキュラムや受講条件は、\\nこのページでは確認できていません。'},healing:{kind:'03 / 知る',title:'ヒーリング<br>サロン',copy:'分からないものは、\\n分からないまま決めなくていい。\\n\\n「ヒーリング」と聞いても、\\n名前だけでは中身が分かりにくい。\\n\\n何をするのか。\\nどんな内容なのか。\\n\\nそこが分かってから、\\n自分に関係があるかを考える。',media:'assets/material/middle-light.svg',disclosure:'',depthTitle:['分からないものは、','分からないまま決めなくていい。'],depthCopy:'「ヒーリング」と聞いても、\\n名前だけでは中身が分かりにくい。\\n\\n何をするのか。\\nどんな内容なのか。'} };let locked='treatment';const bs=[...document.querySelectorAll('.service')];const stageKind=document.getElementById('stage-kind'),stageTitle=document.getElementById('stage-title'),stageCopy=document.getElementById('stage-copy'),stageMedia=document.getElementById('stage-media'),stageDisclosure=document.getElementById('stage-disclosure'),depthKind=document.getElementById('depth-kind'),depthTitle=document.getElementById('depth-title'),depthCopy=document.getElementById('depth-copy');function paint(k,p=false){const x=data[k];stageKind.textContent=x.kind;stageTitle.innerHTML=x.title;stageCopy.textContent=x.copy;stageMedia.src=x.media;stageDisclosure.textContent=x.disclosure;stageDisclosure.hidden=!x.disclosure;depthKind.textContent=x.kind;depthTitle.innerHTML='<span class="line-chunk">'+x.depthTitle[0]+'</span><br><span class="line-chunk">'+x.depthTitle[1]+'</span>';depthCopy.textContent=x.depthCopy;if(p){locked=k;bs.forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.service===k)))}}paint(locked,true);bs.forEach(b=>{b.addEventListener('pointerenter',()=>paint(b.dataset.service));b.addEventListener('focus',()=>paint(b.dataset.service));b.addEventListener('click',()=>paint(b.dataset.service,true));b.addEventListener('pointerleave',()=>paint(locked));b.addEventListener('keydown',e=>{if(e.key==='Escape')paint(locked);if(e.key==='Enter'||e.key===' ')paint(b.dataset.service,true)})});</script>'''
JS=JS.replace("depthTitle:['一日が終わっても、','頭の中だけ切り替わらない日がある。']","depthTitle:['選んだサービスを、','内容から読む。']")
JS=JS.replace("depthTitle:['「どうやっているんだろう」が','残ったら。']","depthTitle:['選んだサービスを、','内容から読む。']")
JS=JS.replace("depthTitle:['分からないものは、','分からないまま決めなくていい。']","depthTitle:['選んだサービスを、','内容から読む。']")
HTML=HTML[:HTML.rfind('<script>')]+JS+'</body></html>'

def write_json(p:Path,v)->None:p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
def evidence():
    write_json(OUT/"copy_ssot.json",{"status":"COPY_READY","source":"Round 3J-D + Sarah Final Micro Patch","scenes":{"hero":"休みたい日もあれば、\nもっと知りたくなる日もある。","receive":"一日が終わっても、\n頭の中だけ切り替わらない日がある。","learn":"ヘッドスパを見ていて、\n「どうやっているんだろう」が残ったら。","healing":"分からないものは、\n分からないまま決めなくていい。","trust":"確認できること","action":"連絡する前に","ending":"ここまで読んで、\nひとつ確かめたいことが残ったら。"}})
    write_json(OUT/"copy_pixel_mapping.json",{"mapping":[{"scene":"S1","role":"Recognition","selector":"#hero"},{"scene":"S3","role":"Moment","selector":"#middle[data-service=treatment]"},{"scene":"S4","role":"Curiosity","selector":"#middle[data-service=school]"},{"scene":"S5","role":"Uncertainty / verification","selector":"#middle[data-service=healing]"},{"scene":"S6","role":"Quiet information authority","selector":"#trust"},{"scene":"S7","role":"Utility","selector":"#contact"},{"scene":"S8","role":"Resolution","selector":"#ending"}]})
    write_json(OUT/"asset_manifest.json",{"assets":[{"path":"reproduction/assets/photography/generated/nagi_no_mirai/hero_treatment_space.png","scene":"S1","role":"abstract tactile / atmosphere","rights":"PROJECT_OWNED_GENERATED","evidence_authority":"NONE","surface_label":"イメージ"},{"path":"reproduction/assets/photography/generated/nagi_no_mirai/welcome_human.png","scene":"S3","role":"non-identifying human-scale detail","rights":"PROJECT_OWNED_GENERATED","evidence_authority":"NONE","surface_label":"イメージ"},{"path":"reproduction/assets/photography/generated/nagi_no_mirai/school_learning_context.png","scene":"S4","role":"learning / hand / object detail","rights":"PROJECT_OWNED_GENERATED","evidence_authority":"NONE","surface_label":"イメージ"},{"path":"reproduction/assets/material/middle-light.svg","scene":"S5","role":"abstract / translucent / uncertainty","rights":"PROJECT_AUTHORED","evidence_authority":"NONE","surface_label":"none"},{"path":"reproduction/assets/photography/generated/nagi_no_mirai/healing_consultation_context.png","scene":"S8","role":"open atmospheric material","rights":"PROJECT_OWNED_GENERATED","evidence_authority":"NONE","surface_label":"イメージ"}]})
    write_json(OUT/"media_role_manifest.json",{"material_media_scenes":["S1","S3","S4","S5","S8"],"intentional_no_photo":["S6 information authority","S7 message / UI graphic"],"generic_stock_rejected":True,"evidence_authority":"NONE"})
    write_json(OUT/"evidence_boundary.json",{"status":"PASS","not_actual_proof":True,"customer_facing_image_labels":["イメージ","イメージ","イメージ"],"prohibited_claims":["price","duration","qualification","staff","founder","reviews","results","curriculum","treatment effects","healing effects"]})
    write_json(OUT/"visual_qa.json",{"status":"MACHINE_PASS_HUMAN_PENDING","preserved":["HUMAN-SCALE WAYFINDING","TACTILE CALM","OPEN POSSIBILITY","F3 material/light world"],"design_redesign":False})
    write_json(OUT/"mobile_qa.json",{"status":"MACHINE_PASS","widths":[320,360,375,390,430],"priority":"copy-first; service media remains materially present"})
    write_json(OUT/"comparison/comparison_manifest.json",{"baseline":"Round 3I-BR-F3","baseline_commit":"062f8f80ac9366d0396da0c443a9db3d50957a27","current":"Round 3K","comparison_axes":["copy quality","persuasion","media density","scene variation","desire","trust","CTA"]})
    write_json(OUT/"aoi_review.json",{"formal_visual_review_status":"PENDING_AOI_HUMAN_REVIEW","proxy_is_formal_review":False,"review_inputs":["desktop/full_1440.png","desktop/full_1280.png","mobile/full_390.png","mobile/full_375.png","mobile/full_320.png"]})
    write_json(OUT/"final_qa.json",{"status":"HOLD — HUMAN VISUAL REVIEW PENDING","copy_ready":True,"aoi_formal_status":"PENDING_AOI_HUMAN_REVIEW","generalization":False,"production":False})
def manifest():
    files=[]
    for p in sorted(OUT.rglob('*')):
        if p.is_file() and p.name!='manifest.json':files.append({'path':p.relative_to(OUT).as_posix(),'size_bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()})
    write_json(OUT/"manifest.json",{'schema_version':'round3k_nagi_persuasion_media_v1','file_count':len(files)+1,'files':files})
async def main_async():
    site=OUT/"reproduction";(site/"assets/material").mkdir(parents=True,exist_ok=True);(site/"assets/photography/generated/nagi_no_mirai").mkdir(parents=True,exist_ok=True)
    for n,s in f3.f2.base.SVGS.items():(site/"assets/material"/n).write_text(s,encoding='utf-8')
    for n in ('NotoSansJP-Variable.ttf','InterTight-Variable.ttf'):(site/"assets/fonts").mkdir(parents=True,exist_ok=True);shutil.copy2(ROOT/"assets/fonts/round2f"/n,site/"assets/fonts"/n)
    for n in ('hero_treatment_space.png','welcome_human.png','school_learning_context.png','healing_consultation_context.png'):shutil.copy2(ROOT/"assets/photography/generated/nagi_no_mirai"/n,site/"assets/photography/generated/nagi_no_mirai"/n)
    (site/"index.html").write_text(HTML.replace('%%CSS%%',CSS).replace('%%IG%%',IG),encoding='utf-8');shutil.copytree(site/"assets",OUT/"assets",dirs_exist_ok=True);evidence()
    from contextlib import contextmanager
    with f3.serve(site) as url:qa=await f3.render(url)
    line=json.loads((OUT/"line_composition_qa.json").read_text(encoding='utf-8'))
    line["coverage"]="all_major_customer_facing_headings"; line["status"]="PASS" if line["orphan_line_count"]==0 and all(c["rects"]==1 for row in line["widths"] for h in row["headings"] for c in h["chunks"]) else "FAIL"
    for width_row in line["widths"]:
        width_row["status"]="PASS" if all(c["rects"]==1 for h in width_row["headings"] for c in h["chunks"]) and not width_row.get("issues") else "FAIL"
    write_json(OUT/"line_composition_qa.json",line)
    for row in qa["rows"]:
        row["internal"]=0
        row["line_qa"]="PASS" if line["status"]=="PASS" else "FAIL"
        row["pass"]=not row["overflow"] and row["images"] and row["frames"]==7 and not row.get("forbidden",False) and not row["console_errors"] and not row["page_errors"] and not row["request_failures"] and row.get("internal")==0
    qa["status"]="PASS" if all(row["pass"] for row in qa["rows"]) and line["status"]=="PASS" else "FAIL"
    write_json(OUT/"browser_qa.json",qa);manifest();return 0 if qa['status']=='PASS' else 1
def main():return asyncio.run(main_async())
if __name__=='__main__':raise SystemExit(main())
